### ISSUE TITLE
Selenium Tests fail with multiple tests per fixture

### ISSUE THREAD

**Issue by danwiesenthal** [miguelgrinberg/flasky#133]
I've been getting an error when I try to use more than one test under the SeleniumTestCase fixture.  I believe it is related to the client/driver not cleaning up properly, or perhaps it is related to the running server in the alternate thread (though it still does receive the request to /shutdown).  

Simple steps to reproduce:  
1) get a fresh clone of the repo
2) copy the test_admin_home_page() function in test_selenium.py, paste it below the original twice, once as test_admin_home_page_duplicate() and again as test_admin_home_page_triplicate(), as though those were two more tests under the SeleniumTestCase fixture
3) run manage.py test.  The original test, test_admin_home_page, succeeds, but both _duplicate and _triplicate fail:
# 
## FAIL: test_admin_home_page_duplicate (test_selenium.SeleniumTestCase)

Traceback (most recent call last):
  File "/Users/me/flasky/tests/test_selenium.py", line 99, in test_admin_home_page_duplicate
    self.client.page_source))
AssertionError: None is not true
# 
## FAIL: test_admin_home_page_triplicate (test_selenium.SeleniumTestCase)

Traceback (most recent call last):
  File "/Users/me/flasky/tests/test_selenium.py", line 120, in test_admin_home_page_triplicate
    self.client.page_source))
AssertionError: None is not true

---

Ran 34 tests in 15.892s

FAILED (failures=2)

This is the cleanest way to reproduce this I see, though for what it's worth I'm seeing several more related issues in the rest of my test suite related to --I think-- Selenium tests not cleaning up properly.  Any thoughts here?  I've tried moving the client (webdriver.Firefox()) out of class-level setup and teardown and into the usual setUp and tearDown, I've tried creating both a class-level client and a test-level client, closing out both at their respective levels of teardown... nothing seems to work yet in that whenever I have multiple Selenium tests (or rerun the same ones with sniffer (https://github.com/jeffh/sniffer/)) the tests seem to get polluted and fail, even though a clean run once through with only the one Selenium test present in the clean repo passes.  Is the Selenium test here leaving something behind that's messing things up?  Or am I misunderstanding how to use Selenium tests, and perhaps they're different from the usual unittest tests in handling of multiple-tests-per-fixture situations?  

Thanks,
Dan

**Comment by miguelgrinberg** [comment]
One problem this test that I wrote in the selenium test case has is that it does not leave things the way they were before the test starts. A very easy way to make that happen would be to add a "logout" action at the end of the test. Then repeating the test would cause no problem, I think.

**Comment by danwiesenthal** [comment]
I agree that the test doesn't seem to be leaving things the way they were before the test starts.  One thing I tried to do to make sure the test fully cleaned up, which may be overkill but I wanted to be extra-sure things were clean, was to hit the /shutdown route, call .close() on the client, db.drop_all() and db.session.remove(), and finally pop the app_context, *all as part of the teardown* (tried this both with class-level as well as test-level teardown), and was quite surprised when *even then* the test still didn't leave things the way they were before the test began.  I'd be quite happy to add a logout action at the end of the test... but would that really help if shutting down the server, killing the client, and flashing the db all didn't do it?

**Comment by miguelgrinberg** [comment]
I think so. Shutting down the server does not kill the login cookie that is stored in the client.
