### ISSUE TITLE
Logging SMTP handler question

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#138]
Hi Miguel,

in config.py you have the code to email admin app error - I want to test that actually works - so I have revised that part and put it in the `class DevelopmentConfig(Config):` but I am not receiving any emails - I can receive other emails sent from the app such as user registration - I know email is working and the admin email has been set - anything I did wrong - how can I make sure this works? Thanks for your help!!

```
    @classmethod
    def init_app(cls, app):
        Config.init_app(app)

        # email errors to the administrators
        import logging
        from logging.handlers import SMTPHandler
        credentials = None
        secure = None
        if getattr(cls, 'MAIL_USERNAME', None) is not None:
            credentials = (cls.MAIL_USERNAME, cls.MAIL_PASSWORD)
            if getattr(cls, 'MAIL_USE_TLS', None):
                secure = ()
        mail_handler = SMTPHandler(
            mailhost=(cls.MAIL_SERVER, cls.MAIL_PORT),
            fromaddr=cls.FLASKY_MAIL_SENDER,
            toaddrs=[cls.FLASKY_ADMIN],
            subject=cls.FLASKY_MAIL_SUBJECT_PREFIX + ' Application Error',
            credentials=credentials,
            secure=secure)
        mail_handler.setLevel(logging.ERROR)
        app.logger.addHandler(mail_handler)
```

**Comment by miguelgrinberg** [comment]
Are you generating an error on purpose to test this? What kind of error? Do you see the error on the console?

**Comment by harrywang** [comment]
Yes. I created an attribute error - the error shows in the console. Is there a better way to create a 500 internal error on purpose to test this? Thanks a lot for your help.

**Comment by miguelgrinberg** [comment]
Use a different logging handler, maybe the one that writes to a file. That will tell you if the problem is in the email logger specifically or on how the logger handler gets attached to the logging instance.

**Comment by harrywang** [comment]
Thanks, Miguel. I used the following code:
```
    app.logger.error('This is a error log test')
    app.logger.info('This is a info log test')

```
to generate errors and got an email. So the code works!! Thanks!

**Comment by jayzhen521** [comment]
@harrywang @miguelgrinberg 
I still find no email is sent. Can you give some tips how to fix it.
My simplified code is:

```
import os
import logging
from logging.handlers import SMTPHandler
from flask import Flask

app = Flask(__name__)

@app.route('/')
def foo():
    app.logger.warning('A warning occurred (%d apples)', 42)
    app.logger.error('An error occurred')
    app.logger.info('Info')
    return "foo"

if __name__ == '__main__':
    credentials = ('admin@wenxee.com', 'my_password')
    secure = ()
    mail_handler = SMTPHandler(
        mailhost=('smtp.mxhichina.com', 465),
        fromaddr='admin@wenxee.com',
        toaddrs=['jizhen_521@hotmail.com'],
        subject='[wx]' + ' Application Error',
        credentials=credentials,
        secure=secure
        )
    mail_handler.setLevel(logging.WARNING)
    app.logger.addHandler(mail_handler)
    app.run()
```

**error log:**
```
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 387, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/handlers.py", line 1010, in emit
    smtp = smtplib.SMTP(self.mailhost, port, timeout=self.timeout)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 338, in connect
    (code, msg) = self.getreply()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 391, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out
Call stack:
  File "server.py", line 29, in <module>
    app.run()
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 777, in inner
    srv.serve_forever()
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 612, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jay/Tests/g_python/b_smtphandler2/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 10, in foo
    app.logger.warning('A warning occurred (%d apples)', 42)
Message: 'A warning occurred (%d apples)'
Arguments: (42,)
127.0.0.1 - - [28/Mar/2018 17:10:54] "GET / HTTP/1.1" 200 -
```

**Comment by miguelgrinberg** [comment]
Your SMTP server does not appear to be responding, this is likely not your script's fault, unless you have misconfigured your server details.

**Comment by jayzhen521** [comment]
@miguelgrinberg Thank you very much!
I used another smtp server which using STARTTSL instead of SSL, it works. Smtp.mxhichina.com cannot support it.
The weird thing is flask-email can send email by ssl in mxhichina!!!

**Comment by wavesailor** [comment]
It seems according to this [article ](https://stackoverflow.com/a/36937462/312089) that SMTPHandler does not work well with TLS . And with SSL you have to basically re-write it.
 Or is there another way to do this?

**Comment by miguelgrinberg** [comment]
@wavesailor I'm not aware of any major problems, certainly not with TLS which is what I tested. The `secure` argument must be set to a tuple to enable TLS. If you don't need to send a certificate, it should be an empty tuple, i.e. `secure=()`.

**Comment by wavesailor** [comment]
@miguel -
What I've read is that SMTPHandler uses smtplib.SMTP() internally and there is no way to rather get it to use smtplib.SMTP_SSL()  to send email using SSL rather than TLS

    On Wednesday, February 20, 2019, 1:09:40 AM EST, Miguel Grinberg <notifications@github.com> wrote:  
 
 
@wavesailor I'm not aware of any major problems, certainly not with TLS which is what I tested. The secure argument must be set to a tuple to enable TLS. If you don't need to send a certificate, it should be an empty tuple, i.e. secure=().

**Comment by dycw** [comment]
As I came across this, I put together a `SMTPHandler` subclass which does this into a package:

- https://github.com/dycw/ssl-smtp-handler
- `pip install ssl-smtp-handler`

Tested and works as of 2021-03, Python 3.6+.
