### ISSUE TITLE
Many_to_Many relationship

### ISSUE THREAD

**Issue by Mohamad1994HD** [miguelgrinberg/flasky#146]
I'm trying to make many_to_many relationship as I understood from the book, between two tables
1) Car_Model
2) Company

Where each car model has more than one companies that its available at, and each company has more than one specific car model, I tried to do it however I think my structure is wrong or there is something am mistaking, if any help with explanation I would appreciate that.

```python
class Association(db.Model):
    __tablename__ = 'Association'
    company_id = db.Column(db.Integer, db.ForeignKey('Companies.id'), primary_key=True)
    model_id = db.Column(db.Integer, db.ForeignKey('Models.id'), primary_key=True)


class Car_Model(db.Model):
    __tablename__ = 'Models'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(10))
    # year
    brand_id = db.Column(db.Integer, db.ForeignKey('Brands.id'))

    company = db.relationship('Association',
                              foreign_keys=[Association.model_id],
                              backref=db.backref('model', lazy='joined'),
                              lazy='dynamic',
                              cascade='all, delete-orphan')
    def __repr__(self):
        return '<Model %r>' % self.name

class Company(db.Model):
    __tablename__ = 'Companies'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), unique=True)
    price = db.Column(db.Integer)

    model = db.relationship('Association',
                            foreign_keys=[Association.company_id],
                            backref=db.backref('company', lazy='joined'),
                            lazy='dynamic',
                            cascade='all, delete-orphan')

    def __repr__(self):
        return '<Company %r>' % self.name
```

Am getting that error:
FlushError: Attempting to flush an item of type <class 'main.Car_Model'> as a member of collection "Company.model". Expected an object of type <class 'main.Association'> or a polymorphic subclass of this type.

**Comment by miguelgrinberg** [comment]
I need the stack trace of your error please.

**Comment by Mohamad1994HD** [comment]
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<string>", line 2, in __init__
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 347, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 754, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 177, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\event\attr.py", line 256, in __call__
    fn(*args, **kw)
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 2872, in _event_on_first_init
    configure_mappers()
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 2768, in configure_mappers
    mapper._post_configure_properties()
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1710, in _post_configure_properties
    prop.init()
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 183, in init
    self.do_init()
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1629, in do_init
    self._setup_join_conditions()
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1704, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1972, in __init__
    self._determine_joins()
  File "C:\Users\Mohamad\flask_venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2076, in _determine_joins
    "specify a 'primaryjoin' expression." % self.prop)
NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Car_Model.company - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
```

**Comment by miguelgrinberg** [comment]
Sorry, but the error does not appear to match the code that you presented above, nor the error message you mentioned in the first post.
