### ISSUE TITLE
Heroku sqlalchemy error

### ISSUE THREAD

**Issue by Mohamad1994HD** [miguelgrinberg/flasky#161]
Dear Miguel,
Am trying with the deployment via heroku platform, however I ran into an error I couldn't understand, after pushing the code and run it remotely on heroku, the app is giving internal server errors (500) due to uninitialized database (no tables), so after running the command:
heroku run python manage.py deploy

it gave me the following trace:

``` python
(EMU_app_venv) C:\Users\Mohamad\PycharmProjects\EMU_app>heroku run python manage.py deploy
Running python manage.py deploy on emu-app... up, run.3978
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> a07ae8f8165b, empty message
INFO  [alembic.runtime.migration] Running upgrade a07ae8f8165b -> cfadf15f7921, empty message
INFO  [alembic.runtime.migration] Running upgrade cfadf15f7921 -> 27046ebd3882, empty message
INFO  [alembic.runtime.migration] Running upgrade 27046ebd3882 -> 8f2f7828bf1d, empty message
INFO  [alembic.runtime.migration] Running upgrade 8f2f7828bf1d -> 7ffc818a24c1, empty message
Traceback (most recent call last):
  File "manage.py", line 42, in <module>
    manager.run()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 25, in deploy
    upgrade()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_migrate/__init__.py", line 235, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/app/migrations/versions/7ffc818a24c1_.py", line 20, in upgrade
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
  File "<string>", line 8, in create_index
  File "<string>", line 3, in create_index
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/operations/ops.py", line 849, in create_index
    return operations.invoke(op)
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 88, in create_index
    operations.impl.create_index(idx)
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/ddl/impl.py", line 206, in create_index
    self._exec(schema.CreateIndex(index))
  File "/app/.heroku/python/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "ix_users_email" already exists
 [SQL: 'CREATE UNIQUE INDEX ix_users_email ON users (email)']

(EMU_app_venv) C:\Users\Mohamad\PycharmProjects\EMU_app>

```

**Comment by miguelgrinberg** [comment]
The error says that there is an index that already exists. You need to review your migrations, you'll probably find that the index has been created already.

**Comment by Mohamad1994HD** [comment]
I have opened the shell remotely and drop_all then create_all then run the deploy function and it gave
```python
Running python manage.py deploy on emu-app... up, run.4714
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

So then I entered the application to register a new user via browser and opened the logs on cmd, it gave me again an error (although it worked on local dev server)

```python


2016-06-19T10:04:30.879788+00:00 app[web.1]: Traceback (most recent call last):
2016-06-19T10:04:30.879801+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/handlers.py", line 934, in emit
2016-06-19T10:04:30.879830+00:00 app[web.1]:     ",".join(self.toaddrs),
2016-06-19T10:04:30.879842+00:00 app[web.1]: TypeError: sequence item 0: expected string, NoneType found
2016-06-19T10:04:30.879842+00:00 app[web.1]: Logged from file app.py, line 1587
2016-06-19T10:04:30.880028+00:00 app[web.1]: Exception on /auth/register [POST]
2016-06-19T10:04:30.880036+00:00 app[web.1]: Traceback (most recent call last):
2016-06-19T10:04:30.880037+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2016-06-19T10:04:30.880038+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-06-19T10:04:30.880039+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-06-19T10:04:30.880039+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-06-19T10:04:30.880040+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-06-19T10:04:30.880051+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-06-19T10:04:30.880052+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-06-19T10:04:30.880052+00:00 app[web.1]:     rv = self.dispatch_request()
2016-06-19T10:04:30.880052+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2016-06-19T10:04:30.880053+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-06-19T10:04:30.880053+00:00 app[web.1]:   File "/app/app/auth/views.py", line 33, in register
2016-06-19T10:04:30.880054+00:00 app[web.1]:     if form.validate_on_submit():
2016-06-19T10:04:30.880054+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_wtf/form.py", line 166, in validate_on_submit
2016-06-19T10:04:30.880055+00:00 app[web.1]:     return self.is_submitted() and self.validate()
2016-06-19T10:04:30.880055+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
2016-06-19T10:04:30.880055+00:00 app[web.1]:     return super(Form, self).validate(extra)
2016-06-19T10:04:30.880056+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
2016-06-19T10:04:30.880056+00:00 app[web.1]:     if not field.validate(self, extra):
2016-06-19T10:04:30.880057+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/wtforms/fields/core.py", line 204, in validate
2016-06-19T10:04:30.880057+00:00 app[web.1]:     stop_validation = self._run_validation_chain(form, chain)
2016-06-19T10:04:30.880058+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
2016-06-19T10:04:30.880058+00:00 app[web.1]:     validator(form, self)
2016-06-19T10:04:30.880059+00:00 app[web.1]:   File "/app/app/auth/forms.py", line 28, in validate_email
2016-06-19T10:04:30.880059+00:00 app[web.1]:     if User.query.filter_by(email=field.data).first():
2016-06-19T10:04:30.880059+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2659, in first
2016-06-19T10:04:30.880060+00:00 app[web.1]:     ret = list(self[0:1])
2016-06-19T10:04:30.880060+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
2016-06-19T10:04:30.880060+00:00 app[web.1]:     return list(res)
2016-06-19T10:04:30.880061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
2016-06-19T10:04:30.880061+00:00 app[web.1]:     return self._execute_and_instances(context)
2016-06-19T10:04:30.880062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
2016-06-19T10:04:30.880062+00:00 app[web.1]:     result = conn.execute(querycontext.statement, self._params)
2016-06-19T10:04:30.880063+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
2016-06-19T10:04:30.880063+00:00 app[web.1]:     return meth(self, multiparams, params)
2016-06-19T10:04:30.880064+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
2016-06-19T10:04:30.880064+00:00 app[web.1]:     return connection._execute_clauseelement(self, multiparams, params)
2016-06-19T10:04:30.880065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
2016-06-19T10:04:30.880065+00:00 app[web.1]:     compiled_sql, distilled_params
2016-06-19T10:04:30.880065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
2016-06-19T10:04:30.880066+00:00 app[web.1]:     context)
2016-06-19T10:04:30.880066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
2016-06-19T10:04:30.880067+00:00 app[web.1]:     exc_info
2016-06-19T10:04:30.880067+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
2016-06-19T10:04:30.880067+00:00 app[web.1]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2016-06-19T10:04:30.880068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
2016-06-19T10:04:30.880068+00:00 app[web.1]:     context)
2016-06-19T10:04:30.880068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
2016-06-19T10:04:30.880069+00:00 app[web.1]:     cursor.execute(statement, parameters)
2016-06-19T10:04:30.880069+00:00 app[web.1]: ProgrammingError: (psycopg2.ProgrammingError) relation "users" does not exist
2016-06-19T10:04:30.880070+00:00 app[web.1]: LINE 2: FROM users
2016-06-19T10:04:30.880070+00:00 app[web.1]:              ^
```

it appears to me that PostgreSQL refuse the validate_email after registering?
please I need help..
is this errors platform dependent ? if so ( is there any easier platform for deploying python)

**Comment by miguelgrinberg** [comment]
When you use `drop_all` you are only dropping the tables the application knows about. In particular, you are not dropping the little table that stores the migration version. For this reason, when you then run `manage.py deploy`, the system thinks it is already migrated to latest revision so it does nothing.

I still claim that there is some sort of inconsistency between the migrations that you have created and the state of your models.

**Comment by Mohamad1994HD** [comment]
So shall I "init" the migration again? Or how can I re-initialize the migrations and let the current state be the starting one... I have used 'stamp heads' although it works but i couldn't understand what does it do? Can you pls explain what am supposed to do

**Comment by miguelgrinberg** [comment]
Start with an empty database. Then apply the migrations and see where is the error. That will point to the migration that is incorrect.

**Comment by Paphra** [comment]
Mine is really disturbing

'''
Exception on /auth/login [POST]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "user" does not exist
LINE 2: FROM "user" 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app/auth/routes.py", line 23, in login
    user = User.query.filter_by(username=username).first()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "user" does not exist
LINE 2: FROM "user" 
             ^

[SQL: SELECT "user".id AS user_id, "user".username AS user_username, "user".email AS user_email, "user".password_hash AS user_password_hash, "user".about_me AS user_about_me, "user".last_seen AS user_last_seen 
FROM "user" 
WHERE "user".username = %(username_1)s 
 LIMIT %(param_1)s]
[parameters: {'username_1': 'paphra', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
'''
I do not know what to do.

**Comment by miguelgrinberg** [comment]
@Paphra the error indicates that you do not have a user table in your database.

**Comment by parismollo** [comment]
> Mine is really disturbing
> 
> ```
> Exception on /auth/login [POST]
> Traceback (most recent call last):
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
>     cursor, statement, parameters, context
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.ProgrammingError: relation "user" does not exist
> LINE 2: FROM "user" 
>              ^
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/app/app/auth/routes.py", line 23, in login
>     user = User.query.filter_by(username=username).first()
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3215, in first
>     ret = list(self[0:1])
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
>     return list(res)
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
>     return self._execute_and_instances(context)
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
>     result = conn.execute(querycontext.statement, self._params)
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
>     return meth(self, multiparams, params)
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
>     distilled_params,
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
>     util.raise_from_cause(sqlalchemy_exception, exc_info)
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
>     raise value.with_traceback(tb)
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
>     cursor, statement, parameters, context
>   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "user" does not exist
> LINE 2: FROM "user" 
>              ^
> 
> [SQL: SELECT "user".id AS user_id, "user".username AS user_username, "user".email AS user_email, "user".password_hash AS user_password_hash, "user".about_me AS user_about_me, "user".last_seen AS user_last_seen 
> FROM "user" 
> WHERE "user".username = %(username_1)s 
>  LIMIT %(param_1)s]
> [parameters: {'username_1': 'paphra', 'param_1': 1}]
> (Background on this error at: http://sqlalche.me/e/f405)
> ```
> 
> I do not know what to do.

Have you solved this issue? I'm having the same... The User table does exists and works locally... so I don't know why in Heroku it doesn't work @miguelgrinberg @Paphra

**Comment by miguelgrinberg** [comment]
@parismollo the fact that you have the table in your local database does not indicate anything about the state of the Postgres database that you use with your Heroku app. The error claims the user table does not exist there.

**Comment by parismollo** [comment]
@miguelgrinberg  Fixed with `heroku run flask db upgrade`.

Thank you !

**Comment by Ko3ch** [comment]
tried the above solution, but threw me this error.


Traceback (most recent call last):
  File "/app/.heroku/python/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 117, in call_factory
    return app_factory(script_info)
  File "/app/app/__init__.py", line 23, in create_app
    app.config.from_object(config_options[config_name])
KeyError: <flask.cli.ScriptInfo object at 0x7f8d6a5d77b8>


here's my create_app

from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

simple = SimpleMDE()
bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    configure_uploads(app,photos)

    return app

**Comment by Ko3ch** [comment]
will appreciate any help

**Comment by GitauHarrison** [comment]
> will appreciate any help

To use `flask db migrate` ensure that you have installed `flask migrate` and initialized it in your application.Then, in your `create_app` factory function, add the argument `db` to `migrate.init_app`.

From:

```python
# Your previous code

def create_app(config_name):
	app = Flask(name)

	app.config.from_object(config_options[config_name])
	config_options[config_name].init_app(app)

	bootstrap.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)
	mail.init_app(app)
	simple.init_app(app)

	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)

	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint,url_prefix = '/auth')

	configure_uploads(app,photos)

return app
```
To:

```python
# Your previous imports
from flask_migrate import Migrate # <-------------------------------------------------------------- new

migrate = Migrate() # <-------------------------------------------------------------- new

def create_app(config_name):
	app = Flask(name)

	app.config.from_object(config_options[config_name])
	config_options[config_name].init_app(app)

	bootstrap.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)
	mail.init_app(app)
	simple.init_app(app)
	migrate.init_app(app, db) # <-------------------------------------------------------------- new

	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)

	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint,url_prefix = '/auth')

	configure_uploads(app,photos)

return app
```

Then, you can run `heroku run flask db upgrade`
