### ISSUE TITLE
BuildError: ('main.user', {'username': u'reezaul.karim'}, None)

### ISSUE THREAD

**Issue by spaceled** [miguelgrinberg/flasky#166]
Hi Miguel,
How can I solve this problem. Can you solved it for me?

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/project/app/auth/views.py", line 20, in unconfirmed
    return render_template('auth/unconfirmed.html')
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/project/app/templates/auth/unconfirmed.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/vagrant/project/app/templates/base.html", line 4, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in t
op-level template code
    {% block doc -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in b
lock "doc"
    {%- block html %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in
block "html"
    {% block body -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in
block "body"
    {% block navbar %}
  File "/vagrant/project/app/templates/base.html", line 31, in block "navbar"
    <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
  File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('main.user', {'username': u'reezaul.karim'}, None)

**Comment by miguelgrinberg** [comment]
Do you have a `user` route in your `main` template? The error seems to suggest you don't have that in your application.

**Comment by spaceled** [comment]
I did not get you. Would you please share where to route **user**. I have _errors.py, __init__.py, views.py_ and _forms.py_ in **main**.

**Comment by miguelgrinberg** [comment]
Look in views.py in your main blueprint. The `main.user` that you are passing to `url_for()` refers to a route called `user` in blueprint `main`. The error is telling you that the route does not exist.

**Comment by spaceled** [comment]
Its done!

Thanks a lot

**Comment by spaceled** [comment]
**Will you please, show me this one how to solve this?**

send: 'ehlo [10.0.2.15]\r\n'
reply: '250-smtp.googlemail.com at your service, [58.97.200.89]\r\n'
reply: '250-SIZE 35882577\r\n'
reply: '250-8BITMIME\r\n'
reply: '250-STARTTLS\r\n'
reply: '250-ENHANCEDSTATUSCODES\r\n'
reply: '250-PIPELINING\r\n'
reply: '250 SMTPUTF8\r\n'
reply: retcode (250); Msg: smtp.googlemail.com at your service, [58.97.200.89]
SIZE 35882577
8BITMIME
STARTTLS
ENHANCEDSTATUSCODES
PIPELINING
SMTPUTF8
send: 'STARTTLS\r\n'
reply: '220 2.0.0 Ready to start TLS\r\n'
reply: retcode (220); Msg: 2.0.0 Ready to start TLS
send: 'ehlo [10.0.2.15]\r\n'
reply: '250-smtp.googlemail.com at your service, [58.97.200.89]\r\n'
reply: '250-SIZE 35882577\r\n'
reply: '250-8BITMIME\r\n'
reply: '250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\r\n'
reply: '250-ENHANCEDSTATUSCODES\r\n'
reply: '250-PIPELINING\r\n'
reply: '250 SMTPUTF8\r\n'
reply: retcode (250); Msg: smtp.googlemail.com at your service, [58.97.200.89]
SIZE 35882577
8BITMIME
AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
ENHANCEDSTATUSCODES
PIPELINING
SMTPUTF8
send: u'mail FROM:<spaceled@gmail.com> size=1752\r\n'
reply: '530-5.5.1 Authentication Required. Learn more at\r\n'
reply: '530 5.5.1  https://support.google.com/mail/answer/14257 by5sm3497195pad.36 - gsmtp\r\n'
reply: retcode (530); Msg: 5.5.1 Authentication Required. Learn more at
5.5.1  https://support.google.com/mail/answer/14257 by5sm3497195pad.36 - gsmtp
send: 'rset\r\n'
reply: '250 2.1.5 Flushed by5sm3497195pad.36 - gsmtp\r\n'
reply: retcode (250); Msg: 2.1.5 Flushed by5sm3497195pad.36 - gsmtp
send: 'quit\r\n'
reply: '221 2.0.0 closing connection by5sm3497195pad.36 - gsmtp\r\n'
reply: retcode (221); Msg: 2.0.0 closing connection by5sm3497195pad.36 - gsmtp
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/vagrant/project/app/email.py", line 8, in send_async_email
    mail.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/usr/lib/python2.7/smtplib.py", line 731, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/m
ail/answer/14257 by5sm3497195pad.36 - gsmtp', u'Flasky Admin <spaceled@gmail.com>')

**Comment by miguelgrinberg** [comment]
Well, the error seems pretty clear to me:

> SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1 https://support.google.com/mail/answer/14257 by5sm3497195pad.36 - gsmtp', u'Flasky Admin spaceled@gmail.com')

Are you providing credentials to your email server? If you are, are they correct?
