### ISSUE TITLE
error error

### ISSUE THREAD

**Issue by caffrey2016** [miguelgrinberg/flasky#169]
```
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    from app import create_app, db
  File "/home/web/flasky/app/__init__.py", line 13, in <module>
    moment = Moment()
  File "/usr/lib/python2.7/site-packages/moment/core.py", line 16, in __init__
    date, formula = parse_date_and_formula(*args)
  File "/usr/lib/python2.7/site-packages/moment/parse.py", line 18, in parse_date_and_formula
    date = datetime(*date)
TypeError: Required argument 'year' (pos 1) not found
```

**Comment by caffrey2016** [comment]
moment = Moment()    这个报错

**Comment by caffrey2016** [comment]
求答案

**Comment by caffrey2016** [comment]
感觉代码很久，我修改了一天，就差这个一个问题不会处理了

**Comment by miguelgrinberg** [comment]
You need to ask your question in the Moment github, you are in the wrong place. This is where you should go: https://github.com/zachwill/moment.
