### ISSUE TITLE
TypeError: 'unicode' does not have the buffer interface

### ISSUE THREAD

**Issue by clebio** [miguelgrinberg/flasky#17]
I'm attempting to use this repo for the first time as I work through the book. I run into an error when trying to log in, after creating a user. I've tried going through the new user registration flow within the app (though I don't have gmail configured) and also tried adding a user as the book describes in chapter eight:

``` bash
$ ./manage.py shell
>>> u = User(email='john@example.com', username='john', password='cat')
>>> db.session.add(u)
>>> db.session.commit()
```

From the terminal, the error shows as:

``` bash
 $ ./manage.py runserver
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
127.0.0.1 - - [04/Jul/2014 19:08:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Jul/2014 19:08:06] "GET /auth/login HTTP/1.1" 200 -
127.0.0.1 - - [04/Jul/2014 19:08:17] "POST /auth/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/caleb/dev/flasky/app/auth/views.py", line 13, in login
    if user is not None and user.verify_password(form.password.data):
  File "/home/caleb/dev/flasky/app/models.py", line 33, in verify_password
    return check_password_hash(self.password_hash, password)
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/werkzeug/security.py", line 224, in check_password_hash
    return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
  File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/werkzeug/security.py", line 117, in safe_str_cmp
    return _builtin_safe_str_cmp(a, b)
TypeError: 'unicode' does not have the buffer interface
```

The full error on the app itself is:

```
TypeError
TypeError: 'unicode' does not have the buffer interface

Traceback (most recent call last)
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/caleb/dev/flasky/app/auth/views.py", line 13, in login
if user is not None and user.verify_password(form.password.data):
File "/home/caleb/dev/flasky/app/models.py", line 33, in verify_password
return check_password_hash(self.password_hash, password)
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/werkzeug/security.py", line 224, in check_password_hash
return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
File "/home/caleb/.virtualenvs/flasky/lib/python2.7/site-packages/werkzeug/security.py", line 117, in safe_str_cmp
return _builtin_safe_str_cmp(a, b)
TypeError: 'unicode' does not have the buffer interface
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by hugoeiji** [comment]
I've updated to 0.9.6 and now the error is also gone :)
