### ISSUE TITLE
sqlite3.OperationalError:  (5a)

### ISSUE THREAD

**Issue by 363549406** [miguelgrinberg/flasky#170]
hope for help ~~!!  I'm new to flask

First , I checkout 5a

```
git checkout 5a
```

then, I run `hello.py` 

```
python hello.py
```

and I got this error

```
(venv) [root@HarryPotter flasky]# python hello.py
/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py:312: SAWarning: Exception attempting to detect unicode returns: OperationalError('(OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\x80\x81\xb0\xfa\x90\x81\xa1\xf8\x80\x81\xae\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  results = set([check_unicode(test) for test in tests])
/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py:312: SAWarning: Exception attempting to detect unicode returns: OperationalError('(OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\xa0\x81\xb5\xf8\xb0\x81\xa9\xf9\x80\x81\xaf\xf8\x80\x81\xa5\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  results = set([check_unicode(test) for test in tests])
Traceback (most recent call last):
  File "hello.py", line 74, in <module>
    db.create_all()
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 856, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 848, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), tables=tables)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3420, in create_all
    tables=tables)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1727, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1720, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1910, in contextual_connect
    self.pool.connect(),
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 338, in connect
    return _ConnectionFairy._checkout(self)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 645, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1058, in _do_get
    return self._create_connection()
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 285, in _create_connection
    return _ConnectionRecord(self)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 416, in __init__
    exec_once(self.connection, self)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 250, in exec_once
    self(*args, **kw)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 260, in __call__
    fn(*args, **kw)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 1219, in go
    return once_fn(*arg, **kw)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 166, in first_connect
    dialect.initialize(c)
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 248, in initialize
    self._check_unicode_description(connection):
  File "/root/pythonapp/Flask_Web_Development/flasky/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 335, in _check_unicode_description
    ]).compile(dialect=self)
sqlite3.OperationalError: near "񐁓񐁌���𐀠�������l": syntax error
```

**Comment by miguelgrinberg** [comment]
Can you please provide the output of the commands `pip freeze` and `git diff`.

**Comment by 363549406** [comment]
I found the problem was : Sqlalchemy can't work with sqlite. Then I changed to mysql database.

When I Google it "sqlalchemy sqlite detect unicode returns OperationalError", I found some people had the same problem.
[here](http://stackoverflow.com/questions/36189950/flask-sql-alchemy-db-create-all-detect-unicode-returns-r)
[here](https://github.com/galaxyproject/galaxy/issues/2343)

**Comment by miguelgrinberg** [comment]
> Sqlalchemy can't work with sqlite

This is totally incorrect. SQLAlchemy does work well with sqlite. I use it all the time. You did not provide the information I asked.

**Comment by 363549406** [comment]
When I said 
> Sqlalchemy can't work with sqlite

I mean in my environment.
I know it works fine with others. And I know there must be something wrong with my environment.

The `pip freeze` and `git diff` informations are as followed:
```
(venv) [root@HarryPotter flasky]# pip freeze
alembic==0.6.2
bleach==1.4
blinker==1.3
colorama==0.2.7
coverage==3.7.1
Flask==0.10.1
Flask-Bootstrap==3.0.3.1
Flask-HTTPAuth==2.7.0
Flask-Login==0.3.1
Flask-Mail==0.9.0
Flask-Migrate==1.1.0
Flask-Moment==0.2.1
Flask-PageDown==0.1.4
Flask-Script==0.6.6
Flask-SQLAlchemy==1.0
Flask-WTF==0.9.4
ForgeryPy==0.1
html5lib==1.0b3
httpie==0.7.2
itsdangerous==0.23
Jinja2==2.7.1
Mako==0.9.1
Markdown==2.3.1
MarkupSafe==0.18
Pygments==1.6
requests==2.1.0
selenium==2.45.0
six==1.4.1
SQLAlchemy==0.9.9
Werkzeug==0.10.4
WTForms==1.0.5
(venv) [root@HarryPotter flasky]# git diff
(venv) [root@HarryPotter flasky]#
```

**Comment by miguelgrinberg** [comment]
Nothing jumps at me, really.

If at all possible, it would be useful if you can test this with a Python 3.3 or newer release. The problem is definitely related to how SQLAlchemy determines unicode support in sqlite. The way this works is different in Python 3, so you may have better luck there.

Also, is your system configured for a non-English language? I wonder if this is a problem caused by the system configuration, because I have used Python 2.x and 3.x both with sqlite and never had problems.

**Comment by nitt10prashant** [comment]
i had issue which was related to unicode 

root/virt/lib/python2.7/site-packages/sqlalchemy/engine/default.py:322: SAWarning: Exception attempting to detect unicode returns: OperationalError('(sqlite3.OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\x80\x81\xb0\xfa\x90\x81\xa1\xf8\x80\x81\xae\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  "detect unicode returns: %r" % de)
/root/virt/lib/python2.7/site-packages/sqlalchemy/engine/default.py:322: SAWarning: Exception attempting to detect unicode returns: OperationalError('(sqlite3.OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\xa0\x81\xb5\xf8\xb0\x81\xa9\xf9\x80\x81\xaf\xf8\x80\x81\xa5\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  "detect unicode returns: %r" % de)
[2018-03-10 11:12:42,642] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/root/virt/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()

issue got resolved after installing following packages
yum install sqlite-devel
pip install pysqlite
