### ISSUE TITLE
SQLAlchemy db.create_all error

### ISSUE THREAD

**Issue by darjun** [miguelgrinberg/flasky#172]
Please help ~~~~

I'm using Ubuntu16.04 python 2.7.12

I follow the steps in chapter5 one by one. When create_all, it just has an ArgumentError:
>>> db.create_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/darjun/python/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 972, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/darjun/python/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 964, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/darjun/python/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 910, in get_engine
    return connector.get_engine()
  File "/home/darjun/python/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 539, in get_engine
    info = make_url(uri)
  File "/home/darjun/python/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 186, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/darjun/python/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 235, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'sqlite::////home/darjun/python/venv/data.sqlite'

**Comment by miguelgrinberg** [comment]
You have two colon characters after`sqlite`. That should be a single colon character, as this is a URL.

**Comment by darjun** [comment]
it  works. thanks

**Comment by Akash0051** [comment]
import sys
from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy import create_engine

Base = declarative_base()


class Restaurant(Base):
    # Create Restaurant Table name#
    __tablename__ = 'restaurant'
    # Inside Restaurant Mappers are Created#
    name = Column(String(80), nullable=False)
    id = Column(Integer, primary_key=True)


class MenuItem(Base):
    # Create Menu Item Table name#
    __tablename__ = 'menu_item'
    # Inside Menu Item Mappers are Created#
    name = Column(String(80), nullable=False)
    id = Column(Integer, primary_key=True)
    course = Column(String(250))
    description = Column(String(250))
    price = Column(String(8))
    restaurant_id = Column(Integer, ForeignKey('Restaurant.id'))
    restaurant = relationship(Restaurant)


####Insert at the end of the file#####

# Create an engine that stores data in the local directory's
# restaurantmenu.db file.
engine = create_engine('sqlite :///restaurantmenu.db')

# Create all tables in the engine. This is equivalent to "Create Table"
# statements in raw SQL.
metadata = MetaData(engine)
Base.metadata.create_all(engine)
  




gets an error

$ python database_setup.py
Traceback (most recent call last):
  File "database_setup.py", line 35, in <module>
    engine = create_engine('sqlite :///restaurantmenu.db')
  File "C:\Python35\lib\site-packages\sqlalchemy-1.1.5-py3.5-win-amd64.egg\sqlalchemy\engine\__init__.py", line 387, in create_engine
  File "C:\Python35\lib\site-packages\sqlalchemy-1.1.5-py3.5-win-amd64.egg\sqlalchemy\engine\strategies.py", line 50, in create
  File "C:\Python35\lib\site-packages\sqlalchemy-1.1.5-py3.5-win-amd64.egg\sqlalchemy\engine\url.py", line 194, in make_url
  File "C:\Python35\lib\site-packages\sqlalchemy-1.1.5-py3.5-win-amd64.egg\sqlalchemy\engine\url.py", line 243, in _parse_rfc1738_args
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'sqlite :///restaurantmenu.db'

**Comment by miguelgrinberg** [comment]
@Akash0051 remove the space between "sqlite" and the colon.

**Comment by Akash0051** [comment]
ok thanks

**Comment by rupav** [comment]
Thanks @miguelgrinberg removing spaces helped my database working 😃

**Comment by fatmazayed** [comment]
thanks :)
engine=create_engine('sqlite:///restaurantmenu.db')
add /// not //

**Comment by LaurianoElmiroDuarte** [comment]
Problem: I played with Pandas and Postgres yesterday and today I had the same problem.
Solution: the parameter <engine> cannot have <'>, I remove the quotes and bingo !!! it worked out .
