### ISSUE TITLE
error while executing

### ISSUE THREAD

**Issue by abhishek1995s** [miguelgrinberg/flasky#186]
abhishek@abhishek-HP-15-Notebook-PC:~/projects/open-event-orga-server-development$ python create_db.py`DATABASE_URL` either not exported or empty
`DATABASE_URL` either not exported or empty
Traceback (most recent call last):
  File "create_db.py", line 35, in <module>
    db.create_all()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/**init**.py", line 972, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 964, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 910, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/**init**.py", line 539, in get_engine
    info = make_url(uri)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 194, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 243, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''

**Comment by miguelgrinberg** [comment]
As the error indicates, you did not set `DATABASE_URL`. You haven't shown me the code, but this suggests the value of this environment variable is the location of your database.
