### ISSUE TITLE
BuildError: ('index', {}, None)

### ISSUE THREAD

**Issue by Thethinktank** [miguelgrinberg/flasky#189]
Hi am trying to follow through to implement the code. I defined the index in app/_init_.py
as but i am getting the following error

```
[2016-10-13 23:16:22,803] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/edward/PycharmProjects/microblog-version /app/__init__.py", line 71, in main
    return render_template('/login.html')
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/edward/PycharmProjects/microblog-version /app/templates/login.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/edward/PycharmProjects/microblog-version /app/templates/base.html", line 30, in top-level template code
    <li><a href="{{ url_for('index') }}">{{ _('Home') }}</a></li>
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 332, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1811, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 322, in url_for
    force_external=external)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1607, in build
    raise BuildError(endpoint, values, method)
BuildError: ('index', {}, None)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 930, in emit
    smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
Logged from file app.py, line 1587
127.0.0.1 - - [13/Oct/2016 23:16:23] "GET / HTTP/1.1" 500 -
```

**Comment by miguelgrinberg** [comment]
Can you show me how the `index` endpoint is defined in your application?

**Comment by Thethinktank** [comment]
Hi thankks

I just appended this code at the last of app/_init_.py code: 

@app.route('/')
def main():
    return render_template('/login.html')

if __name__ == '__main__':
    app.run(port=5002)

the aim is to have a url and first page

**Comment by miguelgrinberg** [comment]
The argument you pass to `url_for` is the function name. In your case that is `main`, not `index`.

**Comment by Thethinktank** [comment]
Thanks

This is now the error

File "/home/thethinktank/PycharmProjects/LearningPython /app/__init__.py", line 67, in <module>
    from app import views, models
  File "/home/thethinktank/PycharmProjects/LearningPython /app/__init__.py", line 67, in <module>
    from app import views, models
  File "/home/thethinktank/PycharmProjects/LearningPython /app/views.py", line 7, in <module>
    from forms import LoginForm, EditForm, PostForm, SearchForm
  File "/home/thethinktank/PycharmProjects/LearningPython /app/forms.py", line 5, in <module>
    from models import User
  File "/home/thethinktank/PycharmProjects/LearningPython /app/models.py", line 11, in <module>
    import flask.ext.whooshalchemy as whooshalchemy
  File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 110, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.whooshalchemy

**Comment by miguelgrinberg** [comment]
I think you need to review how the packaging system in Python works. This last error is simply telling you that a package you are importing is not installed.

**Comment by Thethinktank** [comment]
thanks for the help
However i removed every additional code. just added dependencies from for the platform. the code is ending at: Process finished with exit code 0

how do i define the first page to load and in which file. I am used to this:
@app.route('/')
def main():
    return render_template('index.html')

@app.route('/showSignUp')
def showSignUp():
    return render_template('signup.html')

@app.route('/showSignin')
def showSignin():
    if session.get('user'):
        return render_template('userHome.html')
    else:
        return render_template('signin.html')

if __name__ == "__main__":
    app.run(port=5000) an works fine in previous work
