### ISSUE TITLE
'NoneType' object has no attribute 'delete_cookie'

### ISSUE THREAD

**Issue by AllenBigBear** [miguelgrinberg/flasky#192]
Hello Mr. Grinberg:
        I'm learning your book "Flask Web Development" , now I've deployed my VPS, and now I can visit the index page by IP address .
        But when I tried to click "Login" button to the  /auth/login page , it failed and occurred "Internal Server Error" , I checked the error information .

        Python3.4 + Nginx +Gunicorn

The main issues it showed are :  
1: Exception on /auth/login [GET]
```
2:  [2016-10-17 21:14:13,399] ERROR in app: Exception on /auth/login [GET]
Traceback (most recent call last):
  File "/home/test/deploy/Flasky_on_Github/venv/lib/python3.4/site-packages/flas                                             k/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/test/deploy/Flasky_on_Github/venv/lib/python3.4/site-packages/flas                                             k/app.py", line 1643, in full_dispatch_request
    response = self.process_response(response)
  File "/home/test/deploy/Flasky_on_Github/venv/lib/python3.4/site-packages/flas                                             k/app.py", line 1862, in process_response
    response = handler(response)
  File "/home/test/deploy/Flasky_on_Github/venv/lib/python3.4/site-packages/flas                                             k_login.py", line 467, in _update_remember_cookie
    self._clear_cookie(response)
  File "/home/test/deploy/Flasky_on_Github/venv/lib/python3.4/site-packages/flas                                             k_login.py", line 503, in _clear_cookie
    response.delete_cookie(cookie_name, domain=domain, path=path)
AttributeError: 'NoneType' object has no attribute 'delete_cookie'
```

I was confused currently ...because in the [GET] method , it should only render the login.html to show the LoginForm...

Could you please give us any suggestion ? Thanks a lot!

**Comment by miguelgrinberg** [comment]
What was the return value of the function that handles the /auth/login URL?

**Comment by AllenBigBear** [comment]
Hello Mr. Grinberg , below are my code for /auth/login  URL

And I tried to modify the return of /auth/login       to      return '&lt;p> Test &lt;/p>'
But it didn't work , when I tried to visit /auth/login  page , it still render the base frame of website and displayed the "Internal Server Error"


```
from flask import render_template,redirect,request,url_for,flash
from flask.ext.login import login_user,current_user
from . import auth
from ..models import User
from .forms import LoginForm,RegistrationForm,ChangePasswordForm,PasswordResetRequestForm,PasswordResetForm,ChangeEmailForm
from flask.ext.login import logout_user,login_required
from app import db
from ..email import send_email



@auth.route('/login',methods=['GET','POST'])       
def login():
	form=LoginForm()
	if form.validate_on_submit():
		user=User.query.filter_by(email=form.email.data).first()
		if user is not None and user.verify_password(form.password.data):
			login_user(user,form.remember_me.data)
			return redirect(request.args.get('next')or url_for('main.index'))
		flash('Invalid username or password.')
	return render_template('auth/login.html',form=form)
```




>Below are my login.html code


```
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Flasky - Login{% endblock %}
{% block page_content %}
<div class="page-header">
	<h1>Login</h1>
</div>
<p>
New user?
<a href="{{ url_for('auth.register') }}">
Click here to register
</a>

<div class='col-md-4'>
	{{ wtf.quick_form(form) }}
</div>
<br>
<br>
<br>
<br>
<br>
<a href="{{url_for('auth.password_reset_request')}}">Forget Password?</a>
</p>

{% endblock %}
```


![login url](https://cloud.githubusercontent.com/assets/18681592/19475107/fee6b064-9564-11e6-98cf-cc2cc253e267.jpg)


![error messages](https://cloud.githubusercontent.com/assets/18681592/19475113/05c86670-9565-11e6-8eeb-60aac58b5227.jpg)

**Comment by AllenBigBear** [comment]
Hello Mr. Grinberg : 
      I found the problem finally...............

      The return response of below function .... I added "one more indentation" in the return line.....

      Now I cancelled one , now it works ........... Still thanks for your reply !~

      Have a good day

```
@main.after_app_request
def after_request(response):
	for query in get_debug_queries():
		if query.duration >= current_app.config['FLAKSY_SLOW_DB_QUERY_TIME']:
			current_app.logger.warning('Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n' %
				(query.statement, query.parameters, query.duration,
				query.context))
	return response
```
