### ISSUE TITLE
chap7

### ISSUE THREAD

**Issue by Zhang21** [miguelgrinberg/flasky#221]
On Windows:
from .app import create_app, db 
from .app.models import User, Role
OR:
from flasky.app import ...

Traceback (most recent call last):
  File "C:/GitHub/flasky/chap7/flasky/manage.py", line 6, in <module>
    from .app import create_app, db
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by Zhang21** [comment]
Or:
from app import xxx

**Comment by Zhang21** [comment]
Should I use top-level packges relationship?

**Comment by miguelgrinberg** [comment]
The top level directory is not a package, so you cannot use the relative import. At that level you can only use absolute (`from app import ...`).

**Comment by Zhang21** [comment]
from app import ...
Now, there have other questions.
I do not understand where the procedure refers to this tuple.
Thanks!


C:\GitHub\flasky\venv\Scripts\python.exe C:/GitHub/flasky/chap7/flasky/manage.py
Traceback (most recent call last):
  File "C:/GitHub/flasky/chap7/flasky/manage.py", line 32, in <module>
    manager.run()
  File "C:\GitHub\flasky\venv\lib\site-packages\flask_script\__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "C:\GitHub\flasky\venv\lib\site-packages\flask_script\__init__.py", line 350, in handle
    app_parser = self.create_parser(prog)
  File "C:\GitHub\flasky\venv\lib\site-packages\flask_script\__init__.py", line 193, in create_parser
    command_parser = command.create_parser(name, func_stack=func_stack, parent=self)
AttributeError: 'tuple' object has no attribute 'create_parser'

**Comment by miguelgrinberg** [comment]
This seems to be an issue with how you have defined a command in manage.py, but without seeing your manage.py I cannot tell you exactly what the problem is.
