### ISSUE TITLE
Example 12-11 … add_self_follows():

### ISSUE THREAD

**Issue by macfire** [miguelgrinberg/flasky#23]
I get `TypeError: an integer is required` when trying to run add_self_follows().
First steps taken:

```
(flask) $ git checkout 12e
(flask) $ pip install -r requirements/dev.txt
(flask) $ python manage.py db upgrade 
```

I receive the following Traceback:

```
(flask) $ python manage.py shell
>>> User.add_self_follows()

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "~/flasky/app/models.py", line 112, in add_self_follows
     for user in User.query.all():
  File "~/flasky/flask/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2241, in all
return list(self)
  File "~/flasky/flask/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 72, in instances
rows = [process[0](row, None) for row in fetch]
  File "~/flasky/flask/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 476, in     _instance
    populate_state(state, dict_, row, isnew, attrs)
  File "~/flasky/flask/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 305, in     populate_state
    populator(state, dict_, row)
 File "~/flasky/flask/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 151, in fetch_col
    dict_[key] = row[col]
TypeError: an integer is required
```

Any insight as to what I'm missing?

**Comment by miguelgrinberg** [comment]
Closing due to inactivity. Please reopen if the problem still exists.
