### ISSUE TITLE
python manage.py shell error

### ISSUE THREAD

**Issue by Danceiny** [miguelgrinberg/flasky#250]
Environment: Win10 64bit + virtualenv PY2.7 
When i run `python manage.py shell`,  i got a error like this:
```
C:\Program Files\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:724: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    manager.run()
  File "C:\Program Files\Anaconda2\lib\site-packages\flask_script\__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "C:\Program Files\Anaconda2\lib\site-packages\flask_script\__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\flask_script\commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\flask_script\commands.py", line 261, in run
    embed(banner1=self.banner, user_ns=context)
  File "C:\Program Files\Anaconda2\lib\site-packages\IPython\terminal\embed.py", line 315, in embed
    shell = InteractiveShellEmbed.instance(_call_location_id='%s:%s' % (frame.f_code.co_filename, frame.f_lineno), **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\IPython\terminal\embed.py", line 100, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "C:\Program Files\Anaconda2\lib\site-packages\IPython\terminal\interactiveshell.py", line 397, in __init__
    self.init_prompt_toolkit_cli()
  File "C:\Program Files\Anaconda2\lib\site-packages\IPython\terminal\interactiveshell.py", line 250, in init_prompt_toolkit_cli
    output=create_output(true_color=self.true_color))
  File "C:\Program Files\Anaconda2\lib\site-packages\prompt_toolkit\shortcuts.py", line 112, in create_output
    return ConEmuOutput(stdout)
  File "C:\Program Files\Anaconda2\lib\site-packages\prompt_toolkit\terminal\conemu_output.py", line 29, in __init__

    self.win32_output = Win32Output(stdout)
  File "C:\Program Files\Anaconda2\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
    info = self.get_win32_screen_buffer_info()
  File "C:\Program Files\Anaconda2\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 50, in __init__
    xterm = 'xterm' in os.environ.get('TERM')
TypeError: argument of type 'NoneType' is not iterable
```
  **I forgot whether i  have ever run this command successfully. But this time, i switched cmd/cmd Admin/babun/powershell etc, actually all of them not gonna work.**
Maybe someone can help me fix it ?

**Comment by Danceiny** [comment]
Plus : checkout 11c  already.

**Comment by Danceiny** [comment]
Plus2:  IPython installed in virtualenv already.

**Comment by miguelgrinberg** [comment]
Looks like this is a bug in the Windows support in package `python-prompt-toolkit` (see https://github.com/jonathanslenders/python-prompt-toolkit/commit/99fa7fae61c9b4ed9767ead3b4f9b1318cfa875d). It's been fixed already, so you may need to upgrade this package to a newer version.

**Comment by Danceiny** [comment]
after upgrade to `xterm = 'xterm' in os.environ.get('TERM', '')`, 
 Got a new error, `prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?`

```
C:\Program Files\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:724: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    manager.run()
  File "C:\Program Files\Anaconda2\lib\site-packages\flask_script\__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "C:\Program Files\Anaconda2\lib\site-packages\flask_script\__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\flask_script\commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\flask_script\commands.py", line 261, in run
    embed(banner1=self.banner, user_ns=context)
  File "C:\Program Files\Anaconda2\lib\site-packages\IPython\terminal\embed.py", line 315, in embed
    shell = InteractiveShellEmbed.instance(_call_location_id='%s:%s' % (frame.f_code.co_filename, frame.f_lineno), **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\IPython\terminal\embed.py", line 100, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "C:\Program Files\Anaconda2\lib\site-packages\IPython\terminal\interactiveshell.py", line 397, in __init__
    self.init_prompt_toolkit_cli()
  File "C:\Program Files\Anaconda2\lib\site-packages\IPython\terminal\interactiveshell.py", line 250, in init_prompt_toolkit_cli
    output=create_output(true_color=self.true_color))
  File "C:\Program Files\Anaconda2\lib\site-packages\prompt_toolkit\shortcuts.py", line 112, in create_output
    return ConEmuOutput(stdout)
  File "C:\Program Files\Anaconda2\lib\site-packages\prompt_toolkit\terminal\conemu_output.py", line 29, in __init__
    self.win32_output = Win32Output(stdout)
  File "C:\Program Files\Anaconda2\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
    info = self.get_win32_screen_buffer_info()
  File "C:\Program Files\Anaconda2\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 150, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
```

**Comment by miguelgrinberg** [comment]
Unfortunately there isn't much I can do about this. The IPython console does not appear to be well supported under Windows. I recommend that you ask other IPython users about this. To workaround the problem, I think if you use the standard Python shell you will be fine.
