### ISSUE TITLE
ImportError:cannot import name 'current_app'

### ISSUE THREAD

**Issue by Gladiator566** [miguelgrinberg/flasky#268]
When I try to run this file. The error that comes up is: ImportError:cannot import name 'current_app'. Detials as follows:
Traceback (most recent call last):
  File "G:\Anaconda\lib\site-packages\werkzeug\http.py", line 22, in <module>
    from email.utils import parsedate_tz
  File "C:\Users\lenovo\Desktop\flasky-master\app\email.py", line 2, in <module>
    from flask import current_app, render_template
ImportError: cannot import name 'current_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/flasky-master/app/__init__.py", line 1, in <module>
    from flask import Flask
  File "G:\Anaconda\lib\site-packages\flask\__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "G:\Anaconda\lib\site-packages\werkzeug\__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "G:\Anaconda\lib\site-packages\werkzeug\exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "G:\Anaconda\lib\site-packages\werkzeug\wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "G:\Anaconda\lib\site-packages\werkzeug\http.py", line 24, in <module>
    from email.Utils import parsedate_tz
  File "C:\Users\lenovo\Desktop\flasky-master\app\email.py", line 2, in <module>
    from flask import current_app, render_template
ImportError: cannot import name 'current_app'

Any idea ? Thanks !

**Comment by miguelgrinberg** [comment]
This is an odd error to get. Do you have Flask installed in your environment? My first thought is that your installation is somehow corrupted and missing stuff.

**Comment by Gladiator566** [comment]
Well,I do have Flask installed in my environment(ubuntu16), and I use virtualenv to install relative packages using the requirement.txt. And pip shows that except for six==1.4.1 is versionConflict(the default six i have is 1.10),everything else installed successfully. 
However, it still doesn't work :( 
Is there anything else may contribute to it? Really Thanks!

**Comment by miguelgrinberg** [comment]
I think the best way to confirm that your virtualenv is correct is to trash it and make a brand new one. Also make sure that when you run your application, you either activate the virtualenv, or else use the python interpreter from the virtualenv, not the global one.

**Comment by Gladiator566** [comment]
Got it to work.
Thanks again for the reply Miguel~
