### ISSUE TITLE
send email with errno 10061

### ISSUE THREAD

**Issue by handsomepan** [miguelgrinberg/flasky#287]
i open the email smtp,and send email did not wok

**Comment by miguelgrinberg** [comment]
What error do you get?

**Comment by handsomepan** [comment]
It's shows that Exception in thread Thread-2.
the last line says error:[Errno 10061].
I think this error is about socket and port ,it's confused me

**Comment by handsomepan** [comment]
Thank you, I am a new who learn about flask,and i am stuck in here 2 days,It's hurts my confidence.It's the error information.
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\flasky\app\email.py", line 11, in send_async_email
    mail.send(msg)
  File "C:\flasky\venv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "C:\flasky\venv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "C:\flasky\venv\lib\site-packages\flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "c:\python27\Lib\smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "c:\python27\Lib\smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "c:\python27\Lib\smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "c:\python27\Lib\smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "c:\python27\Lib\socket.py", line 575, in create_connection
    raise err
error: [Errno 10061]

**Comment by handsomepan** [comment]
Now i know why,It's my  mail_server configuration .errno 10061 shows that you app can't connect to the smtp server.Thank you.
