### ISSUE TITLE
Chapter 7 Large Application Structure

### ISSUE THREAD

**Issue by qinf** [miguelgrinberg/flasky#31]
I checkout 7a and then I execute this command: `./manage.py runserver --host 0.0.0.0`
There is an error:
```
Traceback (most recent call last):
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/qinf/flasky/app/main/views.py", line 13, in index
    user = User.query.filter_by(username=form.name.data).first()
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2367, in first
    ret = list(self[0:1])
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
    return list(res)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2453, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/home/qinf/test_flask/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: users u'SELECT users.id AS users_id, users.username AS users_username, users.role_id AS users_role_id \nFROM users \nWHERE users.username = ?\n LIMIT ? OFFSET ?' (u'test', 1, 0)
```
It is an error with the database. It says it has no the table 'users'. 
The code in the directory are:
![qq20150111232901](https://cloud.githubusercontent.com/assets/1277293/5695694/c76f80e8-99e9-11e4-808b-c2b3d6c31ec7.png)

I guess I did not create the database. 
Is the command I run before is wrong?(command: `./manage.py runserver --host 0.0.0.0`)

**Comment by miguelgrinberg** [comment]
Step 7a is the first that uses a multi-file structure. As part of the re-structure the database name changed, so you have to run `./manage.py db upgrade`. This is covered at the very end of chapter 7, section "Database Setup".
