### ISSUE TITLE
API authorization token returned as bytes breaks jsonify() in python3 

### ISSUE THREAD

**Issue by edalee** [miguelgrinberg/flasky#314]
Hi Miguel, 

Been hitting my head against the wall with an issue in my API tests after upgrading to Python3.

The test that breaks is `test_token_auth (test_api.APITestCase)` because of `TypeError: Object of type 'bytes' is not JSON serializable `

I understand the problem is the returned token is deemed to be a byte code in authentication.py get_token function : 
``` 
return jsonify({'token': g.current_user.generate_auth_token(expiration=3600), 'expiration': 3600})
```
I'm unsure how this worked in python2.7 (did it used to be a string) and what has since changed that is now forcing this issue. Do you have any ideas?

Thanks in advance... 

Regards,
Edward

Here is my Traceback:
```
ERROR: test_token_auth (test_api.APITestCase)                                                            
Test token Authenticatation.                                                                             
----------------------------------------------------------------------                                   
Traceback (most recent call last):                                                                       
  File "/home/edward/Development/Python_Dev/elmb_python3/elmb/tests/test_api.py", line 91, in test_token_
auth                                                                                                     
    headers=self._get_api_headers('john@example.com', 'cat'))                                            
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/werkzeug/test.p
y", line 791, in get                                                                                     
    return self.open(*args, **kw)                                                                        
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/testing.p
y", line 127, in open                                                                                    
    follow_redirects=follow_redirects)                                                                   
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/werkzeug/test.p
y", line 764, in open                                                                                    
    response = self.run_wsgi_app(environ, buffered=buffered)                                             
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/werkzeug/test.p
y", line 677, in run_wsgi_app                                                                            
    rv = run_wsgi_app(self.application, environ, buffered=buffered)                                      
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/werkzeug/test.p
y", line 884, in run_wsgi_app                                                                            
    app_rv = app(environ, start_response)                                                                
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/app.py", 
line 1997, in __call__                                                                                   
    return self.wsgi_app(environ, start_response)                                                        
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/app.py", 
line 1985, in wsgi_app                                                                                   
    response = self.handle_exception(e)                                                                  
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/app.py", 
line 1540, in handle_exception                                                                           
    reraise(exc_type, exc_value, tb)                                                                     
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise   
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()         
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)              
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)                
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value           
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()                    
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)                                           
  File "/home/edward/Development/Python_Dev/elmb_python3/elmb/app/api_1_0/authentication.py", line 54, in get_token
    expiration=3600), 'expiration': 3600})          
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),                                           
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)                 
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps                                         
    **kw).encode(obj)     
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode                                         
    chunks = list(chunks) 
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode                                    
    yield from _iterencode_dict(o, _current_indent_level)                                                
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict                               
    yield from chunks     
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode                                    
    o = _default(o)       
  File "/home/edward/Development/Python_Dev/elmb_python3/venv/lib/python3.6/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)       
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default                                        
    o.__class__.__name__) 
TypeError: Object of type 'bytes' is not JSON serializable
```
And here is my freeze:
```
alembic==0.9.6
bleach==2.1.1
blinker==1.4
click==6.7
decorator==4.1.2
Flask==0.12.2
Flask-HTTPAuth==3.2.3
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Migrate==2.1.1
Flask-Moment==0.5.2
Flask-PageDown==0.2.2
Flask-Script==2.0.5
Flask-SQLAlchemy==2.3.2
Flask-Uploads==0.2.1
Flask-WTF==0.14.2
ForgeryPy==0.1
html5lib==1.0b10
httpie==0.9.9
ipdb==0.10.3
ipython==6.2.1
ipython-genutils==0.2.0
itsdangerous==0.24
jedi==0.11.0
Jinja2==2.10
Mako==1.0.7
Markdown==2.6.5
MarkupSafe==1.0
parso==0.1.0
pexpect==4.3.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
PyMySQL==0.7.11
python-dateutil==2.6.1
python-editor==1.0.1
requests==2.13.0
selenium==3.7.0
simplegeneric==0.8.1
six==1.11.0
SQLAlchemy==1.1.15
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.2
WTForms==2.1
```

**Comment by miguelgrinberg** [comment]
Oh, looks like I never updated this in the repo. The token does come as bytes. In Python 2 it does not cause a problem because bytes are strings are implicitly converted, but Python 3 treats bytes and strings as different types, so an explicit conversion is needed. The `generate_auth_token()` function in `models.py` needs to be as follows:

```python
    def generate_auth_token(self, expiration):
        s = Serializer(current_app.config['SECRET_KEY'],
                       expires_in=expiration)
        return s.dumps({'id': self.id}).decode('utf-8')
```

The `decode('utf-8')` at the end converts the bytes to a string. This is safe to use in Python 2, even though it isn't needed there. I'll update the repo, sorry I missed this.

**Comment by miguelgrinberg** [comment]
@edalee Actually, on closer look, I did update this method and is currently correct. Any chance you have an old version of this repository cloned on your computer? If you cloned the repo long ago, it may have been before I fixed this. Re-cloning, or following the instructions on the preface to update your clone should address your issue.

**Comment by edalee** [comment]
@miguelgrinberg Great thanks for the explanation!
Yes it is old, I actually never cloned the repo and worked solely from your book.
I did fix it in my repo -- I just couldn't figure out why it wasn't an issue in python2.7. Having only just moved to python3, I still have lots of learning to do about the nuances between them. Thanks for taking the time in explaining it and sorry for the confusion with your own changes... I will be sure to check your current changes next time. 
Thanks again!
