### ISSUE TITLE
ImportError: cannot import name 'abort'

### ISSUE THREAD

**Issue by vlon** [miguelgrinberg/flasky#318]
Traceback (most recent call last):
  File "models.py", line 1, in <module>
    from werkzeug.security import generate_password_hash, check_password_hash
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/http.py", line 24, in <module>
    from email.Utils import parsedate_tz
  File "/home/josh/tangan/flasky/app/email.py", line 2, in <module>
    from flask import current_app, render_template
  File "/usr/local/lib/python3.5/dist-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
ImportError: cannot import name 'abort'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
    from urllib.request import urlopen
  File "/usr/lib/python3.5/urllib/request.py", line 86, in <module>
    import email
  File "/home/josh/tangan/flasky/app/email.py", line 2, in <module>
    from flask import current_app, render_template
  File "/usr/local/lib/python3.5/dist-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/http.py", line 24, in <module>
    from email.Utils import parsedate_tz
ImportError: No module named 'email.Utils'; 'email' is not a package

**Comment by miguelgrinberg** [comment]
Something in your Flask installation is broken. Try reinstalling Flask from scratch. I also recommend you use a virtual environment instead of installing it globally.

**Comment by vlon** [comment]
hi! I reinstalled ubuntu16.04 and flask. But the problem still here.

**Comment by miguelgrinberg** [comment]
It doesn't look like you are following the instructions in the book to start the application. What are you trying to do by starting `models.py`?

**Comment by miguelgrinberg** [comment]
I'm closing, since you haven't followed up with answers to my questions. Please reopen if you want to continue discussing this issue.

**Comment by buddylove86** [comment]
Hi,  
I am encountering this issue on chapter one, hello world:

venv_flask_project) C:\Users\lovem\flask_project>flask run
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lovem\flask_project\venv_flask_project\Scripts\flask.exe\__main__.py", line 5, in <module>
  File "c:\users\lovem\flask_project\venv_flask_project\lib\site-packages\flask\__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "c:\users\lovem\flask_project\venv_flask_project\lib\site-packages\werkzeug\__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "c:\users\lovem\flask_project\venv_flask_project\lib\site-packages\werkzeug\exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "c:\users\lovem\flask_project\venv_flask_project\lib\site-packages\werkzeug\wrappers.py", line 37, in <module>
    from werkzeug.formparser import FormDataParser, default_stream_factory
  File "c:\users\lovem\flask_project\venv_flask_project\lib\site-packages\werkzeug\formparser.py", line 28, in <module>
    from werkzeug.wsgi import make_line_iter, \
  File "c:\users\lovem\flask_project\venv_flask_project\lib\site-packages\werkzeug\wsgi.py", line 828
    """The WSGI specification requires that all middlewares and gateways
         ^
SyntaxError: invalid syntax

**Comment by miguelgrinberg** [comment]
What version of Python are you using?

**Comment by buddylove86** [comment]
Python 3.6.2

**Comment by buddylove86** [comment]
I am going back to the legacy tutorial, and no issues in that version at Chapter 1

**Comment by buddylove86** [comment]
yet would love a solution if possible

**Comment by miguelgrinberg** [comment]
@buddylove86 Something in your Python installation seems to be broken. I would try reinstalling Python 3.6.

**Comment by buddylove86** [comment]
thank you, I did that and working now

**Comment by miguelgrinberg** [comment]
@gnublet this issue only occurs if the email.py module is in the Python path, which is not the case with this application.

**Comment by Anassyed615** [comment]
Hi! I have a error. 
from werkzeug import abort, redirect
ImportError: cannot import name 'abort' from 'werkzeug' (C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\__init__.py)

**Comment by miguelgrinberg** [comment]
@Anassyed615 have you checked the Werkzeug documentation? This isn't the place to ask Werkzeug questions. I don't really remember where the abort function is located in werkzeug, you just need import it from the correct sub-module.
