### ISSUE TITLE
ImportError: No module named dotenv(when I run in python3.6 and python2.7)

### ISSUE THREAD

**Issue by Alexcn** [miguelgrinberg/flasky#332]
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 478, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1055, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1094, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 316, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 209, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 89, in locate_app
    __import__(module)
  File "/Users/light/workdir/flasky/flasky.py", line 2, in <module>
    from dotenv import load_dotenv
ImportError: No module named dotenv

### when I run in python3.6 and python2.7

**Comment by miguelgrinberg** [comment]
Did you run `pip install python-dotenv`?

**Comment by msudgh** [comment]
I'm seeing this issue too!

**Comment by miguelgrinberg** [comment]
@msudgh look at my question above your comment.

**Comment by msudgh** [comment]
@miguelgrinberg I've installed it and also it'll be appear in pycharm intellisence but while running uwsgi i've got the import error.

**Comment by utkarshsone** [comment]
module 'dotenv' has no attribute 'read_dotenv'

**Comment by miguelgrinberg** [comment]
@utkarshsone try `load_dotenv`

**Comment by adnanrizwee** [comment]
pip install -U python-dotenv

run this code for fix error.

**Comment by BizzyEL** [comment]
> 
> 
> pip install -U python-dotenv
> 
> run this code for fix error.

Unfortunately, this does not fix the issue. I actually think it's a virtual environment issue.

In my case, i tried all methods I could find but to no avail.

However, I fixed this problem by installing the module globally. So, maybe, import has to have some reference globally before looking to find it within the virtual environment.
Just a thought though, I'm a amateur/newbie in this field

**Comment by siddeshdeorukhkar89** [comment]
Yes i encountered same issue.

After installation of this module in virtual environment, it was giving errors such as:

ModuleNotFoundError: No module named 'dotenv'

I installed it globally and also installed in virtual environment it worked fine.

**Comment by 0ctopirate** [comment]
For those using ``flask run`` with this error: if you're sourced in a venv, do a quick ``which flask``. You'll likely find that it's the global binary for flask and not the venv's. This can be fixed by replacing ``flask run`` with ``venv/bin/flask run`` or whatever the path to your venv is.
