### ISSUE TITLE
unittest error

### ISSUE THREAD

**Issue by lwmonster** [miguelgrinberg/flasky#358]
When I do unittest of roles and permission, an error occurs:

```
python manage.py test
test_app_exists (test_basic.BasicsTestCase) ... ok
test_app_is_testing (test_basic.BasicsTestCase) ... ok
test_no_password_getter (test_user_models.UserModelTestCase) ... ok
test_password_salts_random (test_user_models.UserModelTestCase) ... ok
test_password_setter (test_user_models.UserModelTestCase) ... ok
test_password_verification (test_user_models.UserModelTestCase) ... ok
test_roles_and_permissions (test_user_models.UserModelTestCase) ... test roles and permissions
init roles in db
my role: <Role u'Administrator'>
my role: <Role u'Administrator'>
my role: <Role u'Administrator'>
ok

----------------------------------------------------------------------
Ran 7 tests in 2.448s

OK
Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    manager.run()
#balabalabalabalabalabalabala
  File "/Users/liangwei/mywork/pythonwork/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: users.email [SQL: u'INSERT INTO users (email, username, role_id, password_hash, confirmed) VALUES (?, ?, ?, ?, ?)'] [parameters: ('lwmonster@qq.com', None, 2, 'pbkdf2:sha256:50000$oUTKhcSr$10aaf6d12139c4f4e03d6edd6ff4bc7454c6cc716701a0a3dc98bf6248ea6034', 0)] (Background on this error at: http://sqlalche.me/e/gkpj)
```

At the beginning, it shows that all the unittest are OK, but why it report an error of "UNIQUE constraint ",  here it should be doing teardown work, but it seems still doing insert work.

Any clue?

**Comment by miguelgrinberg** [comment]
You clearly aren't using an exact copy of the code in this repository, so I can't really tell you what's wrong. The error means that you are writing a duplicate user with email lwmonster@qq.com. You need to review your unit test class to determine were you are writing this duplicate user. Since the tests all pass, I'm guessing it is outside of the tests, in a `setUp` or `tearDown` method.
