### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_bootstrap'

### ISSUE THREAD

**Issue by dangquangdon** [miguelgrinberg/flasky#359]
Hi, I'm trying to run manage.py as instruction in chapter 7, and I got this issuse:
(venv) C:\Users\Don\project\Web\app>manage.py
Traceback (most recent call last):
  File "C:\Users\Don\project\Web\app\manage.py", line 3, in <module>
    from app import create_app, db
  File "C:\Users\Don\project\Web\app\app\__init__.py", line 2, in <module>
    from flask_bootstrap import Bootstrap
ModuleNotFoundError: No module named 'flask_bootstrap'

I have installed flask bootstrap and it was running well for the previous chapters, but now it stopped working like this. I have tried to uninstall flask bootstrap and reinstall it again but it didn't help.
Could you suggest any solution for this issue ? I can't go on if this is not working.

Thank you very much

**Comment by dangquangdon** [comment]
I don't really understand but when I ran virtualenv from other directory, it worked. however I ran into this problem: when I ran python manage.py test

> Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "C:\Users\Don\project\Web\web_app2\app\__init__.py", line 24, in create_app
    from main import main as main_blueprint
ModuleNotFoundError: No module named 'main'

I thought that it might be because of the directory soI changed that line in __init__.py to : 
from app import main as main_blueprint 

And I got this:

> Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "C:\Users\Don\project\Web\web_app2\app\__init__.py", line 25, in create_app
    app.register_blueprint(main_blueprint)
  File "C:\Users\Don\project\Web\virtual\lib\site-packages\flask\app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Users\Don\project\Web\virtual\lib\site-packages\flask\app.py", line 1102, in register_blueprint
    if blueprint.name in self.blueprints:
AttributeError: module 'app.main' has no attribute 'name'

I've been using the exact same code lines as the book

Thank you very much

**Comment by miguelgrinberg** [comment]
If you are running from a directory that is not the top-level directory of the application, then you need to add that directory to the Python path. Set an environment variable `PYTHONPATH=<the directory where flasky is located>` and then you should be able to start the app from another directory.

**Comment by dangquangdon** [comment]
I have managed to run virtualenv from the top level directory ofthe application but I still got this:

> Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "C:\Users\Don\project\Web\web_app2\app\__init__.py", line 24, in create_app
    from main import main as main_blueprint
ModuleNotFoundError: No module named 'main'

I have the same directory structure as it's shown in the book and in your github.

**Comment by miguelgrinberg** [comment]
Are you starting your app from the `C:\Users\Don\project\Web\web_app2` directory?
Do you have a `C:\Users\Don\project\Web\web_app2\app\main` subdirectory?
Do you have a `__init__.py` file in that subdirectory?
Does that `__init__.py` file have a `main = Blueprint(...)` line in it?

I suspect one or more of the above questions have "no" answer, which would explain the import error.

**Comment by dangquangdon** [comment]
1. Yes I run from web_app2 directory

> Directory of C:\Users\Don\project\Web\web_app2

25-May-18  10:08 AM    <DIR>          .
25-May-18  10:08 AM    <DIR>          ..
24-May-18  08:30 PM    <DIR>          app
24-May-18  02:58 PM             1,301 config.py
21-May-18  11:26 PM            28,672 data.sqlite
24-May-18  04:21 PM             3,409 helloweb2.py
24-May-18  10:56 PM               721 manage.py
21-May-18  11:26 PM    <DIR>          migrations
24-May-18  04:02 PM               500 requirements.txt
24-May-18  04:16 PM    <DIR>          tests
25-May-18  10:08 AM    <DIR>          venv
24-May-18  04:58 PM    <DIR>          __pycache__
               5 File(s)         34,603 bytes
               7 Dir(s)  28,751,192,064 bytes free
2. Yes I do have the main subdirectory

> Directory of C:\Users\Don\project\Web\web_app2\app

24-May-18  08:30 PM    <DIR>          .
24-May-18  08:30 PM    <DIR>          ..
24-May-18  11:35 PM    <DIR>          main
24-May-18  11:35 PM               614 models.py
20-May-18  01:02 AM    <DIR>          static
20-May-18  07:30 PM    <DIR>          templates
25-May-18  10:12 AM               699 __init__.py
25-May-18  10:12 AM    <DIR>          __pycache__
               2 File(s)          1,313 bytes
               6 Dir(s)  28,750,741,504 bytes free
3. Yes I have the __init__.py in there

>  Directory of C:\Users\Don\project\Web\web_app2\app\main

24-May-18  11:35 PM    <DIR>          .
24-May-18  11:35 PM    <DIR>          ..
24-May-18  11:36 PM               262 errors.py
24-May-18  11:35 PM               251 forms.py
24-May-18  03:37 PM             1,015 views.py
24-May-18  11:26 PM                98 __init__.py
24-May-18  11:36 PM    <DIR>          __pycache__
               4 File(s)          1,626 bytes
               3 Dir(s)  28,750,733,312 bytes free
4. Yes, I have made the __init__.py exactly the same as instructed:

> from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

**Comment by greyli** [comment]
Maybe you should import the blueprint object with this:
```py
from app.main import main as main_blueprint
```
Can you provide the full directory tree? It will help to find out the problem.
