### ISSUE TITLE
Need some illustration for the faker in 11c

### ISSUE THREAD

**Issue by thunderbang** [miguelgrinberg/flasky#362]
Dear miguelgrinberg:
As faker was used here instead of forgerypy in the book, the fake.py was missing some illustration.
I think the fake.py should be runned to add some fake users and posts into the db. But in my case, something wrong happpened like this. but the email.py is ok since everything works well before. Don't know why

`Traceback (most recent call last):
File "C:\Users\Administrator\PycharmProjects\flask_book\venv\lib\site-packages\werkzeug\http.py", line 22, in
from email.utils import parsedate_tz
File "C:\Users\Administrator\PycharmProjects\flask_book\app\email.py", line 2, in
from flask import current_app, render_template
ImportError: cannot import name 'current_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/Users/Administrator/PycharmProjects/flask_book/app/fake.py", line 4, in
from app import db
File "C:\Users\Administrator\PycharmProjects\flask_book\app_init_.py", line 1, in
from flask import Flask
File "C:\Users\Administrator\PycharmProjects\flask_book\venv\lib\site-packages\flask_init_.py", line 17, in
from werkzeug.exceptions import abort
File "C:\Users\Administrator\PycharmProjects\flask_book\venv\lib\site-packages\werkzeug_init_.py", line 151, in
import('werkzeug.exceptions')
File "C:\Users\Administrator\PycharmProjects\flask_book\venv\lib\site-packages\werkzeug\exceptions.py", line 71, in
from werkzeug.wrappers import Response
File "C:\Users\Administrator\PycharmProjects\flask_book\venv\lib\site-packages\werkzeug\wrappers.py", line 26, in
from werkzeug.http import HTTP_STATUS_CODES,
File "C:\Users\Administrator\PycharmProjects\flask_book\venv\lib\site-packages\werkzeug\http.py", line 24, in
from email.Utils import parsedate_tz
File "C:\Users\Administrator\PycharmProjects\flask_book\app\email.py", line 2, in
from flask import current_app, render_template
ImportError: cannot import name 'current_app'

Process finished with exit code 1```

**Comment by miguelgrinberg** [comment]
> As faker was used here instead of forgerypy in the book

No, you are mixing up the code for the 1st and 2nd editions of the book. The 1st edition uses forgerypy, the 2nd edition uses Faker. The code for the 1st edition of the book is at https://github.com/miguelgrinberg/flasky-first-edition. You should use that code if you are working with the 1st edition.

**Comment by thunderbang** [comment]
Oops...thought the book I'm using was the latest one. Thanks a lot. This is a really fantastic book.
