### ISSUE TITLE
8e: send confirmed email failed.

### ISSUE THREAD

**Issue by MarinZhang** [miguelgrinberg/flasky#375]
This morning , the code runned normally.(can normally send email).
But this afternoon there is no change to code.App can't send email. 
This is the report:

> 127.0.0.1 - - [11/Aug/2018 14:03:11] "GET /auth/confirm HTTP/1.1" 302 -
127.0.0.1 - - [11/Aug/2018 14:03:11] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [11/Aug/2018 14:03:11] "GET /auth/unconfirmed HTTP/1.1" 200 -
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marin/PycharmProjects/flask-hand/app/email.py", line 9, in send_async_email
    mail.send(msg)
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/site-packages/flask_mail.py", line 415, in send
    with self.connect() as connection:
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/site-packages/flask_mail.py", line 123, in __enter__
    self.host = self.configure_host()
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/site-packages/flask_mail.py", line 137, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/home/marin/anaconda3/envs/flasky/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by miguelgrinberg** [comment]
This has nothing to do with the application, your email server cannot be reached, it seems to be down.

**Comment by MarinZhang** [comment]
@miguelgrinberg Thank you for your reply.
It turns out that this issue indeed has nothing with the application.(The email function is normal now)

About " your email server cannot be reached, it seems to be down.", this is mail config:
> MAIL_SERVER = 'smtp.googlemail.com'

and I use shadowsocks as ip proxy( Because of Chinese firewall), with it I can reach google.
So why sometimes I can't reach google email server?(I mean the proxy is ok, the config is ok, I really can't figure out what is the problem)

**Comment by miguelgrinberg** [comment]
It's really hard to say. Maybe gmail was down for a short window of time? I have seen occasional problems connecting to gmail as well, it does happen.

**Comment by ckr815** [comment]
@kolacat FLASKY_MAIL_SENDER is just the sender, why it should be equal to MAIL_USERNAME.
