### ISSUE TITLE
SqlAlchemy problem inside celery when deploying on heroku

### ISSUE THREAD

**Issue by valentin-ballester** [miguelgrinberg/flasky#410]
Helo Miguel, i deployed my app and i am starting a startup thanks to your tutorials which give me the confidence to start developing my idea. My app is online but the celery task aren't working. I have a psycopg2 operational error:

`SSL SYSCALL error: EOF detected`

I think that the problem is generated by some things i did wrong when working with sqlalchemy but im not sure. So here i will recap the things that might be causing trouble.

**1)** im using:

`    with app.app_context():`

at the beggining of the celery task, i dont know if it is the correct way to pass the context to the task.

**2)** this one i think is the real problem:

I think i  dont fully understand how to work properly with sqlalchemy. I noticed that first i had a problem when trying to acces a query atributes after a commit so i disabled expiring_on_commit because i have also do some ` socket.emit ` from this tasks and i couldn't send a emit before commiting. BUT i remove all session when the task ends and also in the socket functions using  `db.session.remove()`.

> some say in the formus that doing  db.engine.dispose() on every task creation solves the problem but i dont even understand why should it solve it and i think my problem goes deeper but maybe im actually working well with sqlalchemy and indeed that solves the problem. 

3)another possible cause of the problem is that im also doing things like:

obj1=query...
commit()
emit({obj1.id})
obj2 = query(filter_by=obj1)
obj3 = obj1.name
commit()
remove()

that was a illustration of the things that my code do, because sometimes i call a function that maybe emits but before emiting i need to commit (this example i give it above) so the user detect new changes when is redirected, etc. but then i need to access the atributes of that query and i dont know i thought that disabling expire_on_commit and db.session.remove() at the end would partially solve my problem but aparently not or im doing something else wrong.

I think the problem is there but maybe is somewhere else... **i would like to give you access to my private rep on github so you can see and maybe give me a push in the correct way of working with flask-sqlalchemy.** so if you are interested let me know im kinda stuck with this.

**Comment by miguelgrinberg** [comment]
Can I see a stacktrace please?

**Comment by valentin-ballester** [comment]
ok so aparently some work well and some give a type of error of unexpected closing and some of bad decryption, i dont know, now it doesnt seem to appear the original error.

2019-03-05T18:14:30.179505+00:00 app[worker.1]: [2019-03-05 18:14:30,173: INFO/MainProcess] Received task: app.SearchEngine.order_timeout[69fb7a79-1a4d-44cd-b1dd-3843001d132f]  ETA:[2019-03-05 18:15:20.038113+00:00] 
2019-03-05T18:14:30.375159+00:00 app[worker.1]: [2019-03-05 18:14:30,262: INFO/MainProcess] Received task: app.SearchEngine.asignation_timeout[bfd31c8d-bc25-4841-b1fe-06ba293376a5]  ETA:[2019-03-05 18:14:40.223113+00:00] 
2019-03-05T18:14:40.686492+00:00 app[worker.1]: [2019-03-05 18:14:40,685: WARNING/ForkPoolWorker-3] AFTER TASK PUBLISH
2019-03-05T18:14:40.697438+00:00 app[worker.1]: [2019-03-05 18:14:40,696: INFO/ForkPoolWorker-3] Task app.SearchEngine.asignation_timeout[bfd31c8d-bc25-4841-b1fe-06ba293376a5] succeeded in 0.4625552839715965s: None
2019-03-05T18:14:40.705248+00:00 app[worker.1]: [2019-03-05 18:14:40,702: INFO/MainProcess] Received task: app.SearchEngine.aviable_check[175aa7bd-6dde-41bf-90a5-f7ab0eb9789d]  ETA:[2019-03-05 18:14:55.519561+00:00]
2019-03-05T18:14:55.605201+00:00 app[worker.1]:     cursor.execute(statement, parameters)
2019-03-05T18:14:55.605203+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
2019-03-05T18:14:55.605205+00:00 app[worker.1]:     state = conn.poll()
2019-03-05T18:14:55.605207+00:00 app[worker.1]: psycopg2.OperationalError: server closed the connection unexpectedly
2019-03-05T18:14:55.605209+00:00 app[worker.1]: 	This probably means the server terminated abnormally
2019-03-05T18:14:55.605211+00:00 app[worker.1]: 	before or while processing the request.
2019-03-05T18:14:55.605212+00:00 app[worker.1]: 
2019-03-05T18:14:55.605214+00:00 app[worker.1]: 
2019-03-05T18:14:55.605216+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2019-03-05T18:14:55.605217+00:00 app[worker.1]: 
2019-03-05T18:14:55.605218+00:00 app[worker.1]: Traceback (most recent call last):
2019-03-05T18:14:55.605220+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
2019-03-05T18:14:55.605222+00:00 app[worker.1]:     R = retval = fun(*args, **kwargs)
2019-03-05T18:14:55.605224+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
2019-03-05T18:14:55.605225+00:00 app[worker.1]:     return self.run(*args, **kwargs)
2019-03-05T18:14:55.605227+00:00 app[worker.1]:   File "/app/app/SearchEngine.py", line 272, in aviable_check
2019-03-05T18:14:55.605229+00:00 app[worker.1]:     aviable_checking(client_id, user_id, *args, **kwargs)
2019-03-05T18:14:55.605231+00:00 app[worker.1]:   File "/app/app/SearchEngine.py", line 278, in aviable_checking
2019-03-05T18:14:55.605232+00:00 app[worker.1]:     user = User.query.filter_by(id=user_id).first()
2019-03-05T18:14:55.605234+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2895, in first
2019-03-05T18:14:55.605235+00:00 app[worker.1]:     ret = list(self[0:1])
2019-03-05T18:14:55.605237+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
2019-03-05T18:14:55.605239+00:00 app[worker.1]:     return list(res)
2019-03-05T18:14:55.605240+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
2019-03-05T18:14:55.605242+00:00 app[worker.1]:     return self._execute_and_instances(context)
2019-03-05T18:14:55.605243+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
2019-03-05T18:14:55.605245+00:00 app[worker.1]:     result = conn.execute(querycontext.statement, self._params)
2019-03-05T18:14:55.605246+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
2019-03-05T18:14:55.605248+00:00 app[worker.1]:     return meth(self, multiparams, params)
2019-03-05T18:14:55.605250+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
2019-03-05T18:14:55.605251+00:00 app[worker.1]:     return connection._execute_clauseelement(self, multiparams, params)
2019-03-05T18:14:55.605253+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
2019-03-05T18:14:55.605254+00:00 app[worker.1]:     compiled_sql, distilled_params
2019-03-05T18:14:55.605256+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
2019-03-05T18:14:55.605257+00:00 app[worker.1]:     context)
2019-03-05T18:14:55.605259+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
2019-03-05T18:14:55.605260+00:00 app[worker.1]:     exc_info
2019-03-05T18:14:55.605262+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
2019-03-05T18:14:55.605264+00:00 app[worker.1]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2019-03-05T18:14:55.605266+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
2019-03-05T18:14:55.605267+00:00 app[worker.1]:     raise value.with_traceback(tb)
2019-03-05T18:14:55.605269+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
2019-03-05T18:14:55.605270+00:00 app[worker.1]:     context)
2019-03-05T18:14:55.605272+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
2019-03-05T18:14:55.605273+00:00 app[worker.1]:     cursor.execute(statement, parameters)
2019-03-05T18:14:55.605275+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
2019-03-05T18:14:55.605276+00:00 app[worker.1]:     state = conn.poll()
2019-03-05T18:14:55.605278+00:00 app[worker.1]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
2019-03-05T18:14:55.605280+00:00 app[worker.1]: 	This probably means the server terminated abnormally
2019-03-05T18:14:55.605281+00:00 app[worker.1]: 	before or while processing the request.
2019-03-05T18:14:55.605336+00:00 app[worker.1]:  [SQL: 'SELECT "user".id AS user_id, "user".username AS user_username, "user".email AS user_email, "user".password_hash AS user_password_hash, "user".user_type AS user_user_type, "user".aviable AS user_aviable, "user".in_cooldown AS user_in_cooldown, "user".open_sockets AS user_open_sockets, "user".system_cooldown AS user_system_cooldown, "user".eta_cooldown AS user_eta_cooldown \nFROM "user" \nWHERE "user".id = %(id_1)s \n LIMIT %(param_1)s'] [parameters: {'id_1': 5, 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/e3q8)
2019-03-05T18:14:06+00:00 app[heroku-redis]: source=REDIS addon=redis-perpendicular-46171 sample#active-connections=13 sample#load-avg-1m=0.175 sample#load-avg-5m=0.145 sample#load-avg-15m=0.14 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664272kB sample#memory-free=12840132kB sample#memory-cached=1029004kB sample#memory-redis=643272bytes sample#hit-rate=0.039216 sample#evicted-keys=0
2019-03-05T18:15:20.103579+00:00 app[worker.1]: [2019-03-05 18:15:20,101: ERROR/ForkPoolWorker-6] Task app.SearchEngine.order_timeout[69fb7a79-1a4d-44cd-b1dd-3843001d132f] raised unexpected: OperationalError('(psycopg2.OperationalError) SSL error: decryption failed or bad record mac\n',)
2019-03-05T18:15:20.103593+00:00 app[worker.1]: Traceback (most recent call last):
2019-03-05T18:15:20.103596+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
2019-03-05T18:15:20.103602+00:00 app[worker.1]:     context)
2019-03-05T18:15:20.103604+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
2019-03-05T18:15:20.103606+00:00 app[worker.1]:     cursor.execute(statement, parameters)
2019-03-05T18:15:20.103608+00:00 app[worker.1]: psycopg2.OperationalError: SSL error: decryption failed or bad record mac
2019-03-05T18:15:20.103610+00:00 app[worker.1]: 
2019-03-05T18:15:20.103611+00:00 app[worker.1]: 
2019-03-05T18:15:20.103613+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2019-03-05T18:15:20.103615+00:00 app[worker.1]: 
2019-03-05T18:15:20.103617+00:00 app[worker.1]: Traceback (most recent call last):
2019-03-05T18:15:20.103619+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
2019-03-05T18:15:20.103620+00:00 app[worker.1]:     R = retval = fun(*args, **kwargs)
2019-03-05T18:15:20.103622+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
2019-03-05T18:15:20.103624+00:00 app[worker.1]:     return self.run(*args, **kwargs)
2019-03-05T18:15:20.103625+00:00 app[worker.1]:   File "/app/app/SearchEngine.py", line 421, in order_timeout
2019-03-05T18:15:20.103627+00:00 app[worker.1]:     order_timeouting(order_id)
2019-03-05T18:15:20.103629+00:00 app[worker.1]:   File "/app/app/SearchEngine.py", line 427, in order_timeouting
2019-03-05T18:15:20.103631+00:00 app[worker.1]:     order = Order.query.filter_by(id=order_id).first()
2019-03-05T18:15:20.103632+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2895, in first
2019-03-05T18:15:20.103634+00:00 app[worker.1]:     ret = list(self[0:1])
2019-03-05T18:15:20.103636+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
2019-03-05T18:15:20.103638+00:00 app[worker.1]:     return list(res)
2019-03-05T18:15:20.103639+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
2019-03-05T18:15:20.103641+00:00 app[worker.1]:     return self._execute_and_instances(context)
2019-03-05T18:15:20.103643+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
2019-03-05T18:15:20.103644+00:00 app[worker.1]:     result = conn.execute(querycontext.statement, self._params)
2019-03-05T18:15:20.103646+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
2019-03-05T18:15:20.103648+00:00 app[worker.1]:     return meth(self, multiparams, params)
2019-03-05T18:15:20.103650+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
2019-03-05T18:15:20.103652+00:00 app[worker.1]:     return connection._execute_clauseelement(self, multiparams, params)
2019-03-05T18:15:20.103653+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
2019-03-05T18:15:20.103655+00:00 app[worker.1]:     compiled_sql, distilled_params
2019-03-05T18:15:20.103657+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
2019-03-05T18:15:20.103677+00:00 app[worker.1]:     context)
2019-03-05T18:15:20.103678+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
2019-03-05T18:15:20.103680+00:00 app[worker.1]:     exc_info
2019-03-05T18:15:20.103682+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
2019-03-05T18:15:20.103684+00:00 app[worker.1]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2019-03-05T18:15:20.103686+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
2019-03-05T18:15:20.103687+00:00 app[worker.1]:     raise value.with_traceback(tb)
2019-03-05T18:15:20.103689+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
2019-03-05T18:15:20.103691+00:00 app[worker.1]:     context)
2019-03-05T18:15:20.103703+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
2019-03-05T18:15:20.103705+00:00 app[worker.1]:     cursor.execute(statement, parameters)
2019-03-05T18:15:20.103706+00:00 app[worker.1]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL error: decryption failed or bad record mac
2019-03-05T18:15:20.103717+00:00 app[worker.1]:  [SQL: 'SELECT "order".id AS order_id, "order".creator AS order_creator, "order".creation_time AS order_creation_time, "order".for_client AS order_for_client, "order".aborted_time AS order_aborted_time, "order".is_urgent AS order_is_urgent, "order".is_emergency AS order_is_emergency, "order".unknown_destiny AS order_unknown_destiny, "order".order_type AS order_order_type, "order".from_adress AS order_from_adress, "order".to_adress AS order_to_adress, "order".extra AS order_extra, "order".pacient_name AS order_pacient_name, "order".timeout AS order_timeout, "order".rounds AS order_rounds \nFROM "order" \nWHERE "order".id = %(id_1)s \n LIMIT %(param_1)s'] [parameters: {'id_1': 10, 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by valentin-ballester** [comment]
is that what you needed?

**Comment by miguelgrinberg** [comment]
This is the important problem in this error:

```
2019-03-05T18:14:55.605207+00:00 app[worker.1]: psycopg2.OperationalError: server closed the connection unexpectedly
2019-03-05T18:14:55.605209+00:00 app[worker.1]: This probably means the server terminated abnormally
```

Your server must have gotten offline, or doesn't have a reliable connection.

**Comment by valentin-ballester** [comment]
and what may it be causing it ?

**Comment by valentin-ballester** [comment]
i noticed that it say i have 13 open connections with redis, that is weird or not ?

source=REDIS addon=redis-perpendicular-46171 sample#active-connections=13 sample#load-avg-1m=0.175 sample#load-avg-5m=0.145 sample#load-avg-15m=0.14 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664272kB sample#memory-free=12840132kB sample#memory-cached=1029004kB sample#memory-redis=643272bytes sample#hit-rate=0.039216 sample#evicted-keys=0

**Comment by miguelgrinberg** [comment]
I don't know, you may want to look for Postgres logs to see if there is anything interesting in there. Redis is probably not related to this problem, the error is from Postgres.

**Comment by valentin-ballester** [comment]
I will go on from here and i will keep you updated

**Comment by valentin-ballester** [comment]
i couldnt find a proper solution, and as my free plan i cant access heroku postgress logs

**Comment by valentin-ballester** [comment]
I found a tutorial where instead of db.session.remove() the tutorial maker ought to do a db.engine.dispose() my question is what does it difference them ?

**Comment by valentin-ballester** [comment]
so maybe that solves the problem because as we saw the celery task connect well to the db at the first task but even the second task start to have problems connecting to it.

**Comment by valentin-ballester** [comment]
no difference, except now it doesnt appear to lost connection, just the other 2 warnings the EOF and the decryption

**Comment by miguelgrinberg** [comment]
The free postgres database is very limited, you are probably going over the max connection limit.

**Comment by valentin-ballester** [comment]
that is a possibility, im going to take out the dispose part, and just leave it as it was and im going to upgrade it but i dont understand why some work and some not, if just 1 celery task run at a time there should be just 1 session for every task, maybe they are expensive task.

taking that 'illustration' of how i work with my database isnt a problem making multiple queries inside a session and committing without expiring a problem ? does it create multiple connections ? is a benefit using expunge if my goal after the commit is just to acces some atributes of the query ? sorry im a bit confused

**Comment by valentin-ballester** [comment]
and by the way thanks for your time and commitment to helping me

**Comment by miguelgrinberg** [comment]
Are you using Flask-SQLAlchemy? This extension manages a separate pool of connections in each process, so you may end up with more connections that you think you have. Not having visibility into the Postgres database stats and logs is a problem for debugging this.

**Comment by valentin-ballester** [comment]
yes, i will upgade heroku plan
