### ISSUE TITLE
BuildError: ('main.index', {}, None)

### ISSUE THREAD

**Issue by dayiguizhen** [miguelgrinberg/flasky#42]
the code in app/auth/views.py is 
     if user is not None and user.verify_password(form.password.data):
            login_user(user,form.remember_me.data);
            return redirect(request.args.get('next') or url_for('main.index'));

the code in app/main/views.py is 
@main.route('/',methods=['GET','POST'])
def index():
	form = NameForm();
	if form.validate_on_submit():
		return redirect(url_for('.index'))
	return render_template('index.html',form=form,name=session.get('name'),known=session.get('known',False),current_time=datetime.utcnow());

the tree of flask is 
../flaskr/
├── app
│   ├── auth
│   │   ├── forms.py
│   │   ├── forms.pyc
│   │   ├── __init__.py
│   │   ├── __init__.pyc
│   │   ├── views.py
│   │   └── views.pyc
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── main
│   │   ├── errors.py
│   │   ├── __init__.py
│   │   └── views.py
│   ├── models.py
│   ├── models.pyc
│   └── templates
│       ├── auth
│       │   └── login.html
│       ├── base.html
│       └── index.html

**Comment by miguelgrinberg** [comment]
Add the complete stack trace of the error, please.

**Comment by dayiguizhen** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yzxu/py/flaskr/app/auth/views.py", line 20, in login
    return redirect(request.args.get('next') or url_for('main.index'));
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('main.index', {}, None)

**Comment by miguelgrinberg** [comment]
Is the name of your main blueprint `'main'`? The error is basically saying that there is no route called `main.index`. It seems you have a `index` route, so I wonder if the name of your blueprint is not `main`.

**Comment by dayiguizhen** [comment]
Is the main blueprint you say in app/main/__init__.py?
The code in my app/main/__init__.py is

from flask import Blueprint

main = Blueprint('main',__name__);

from . import views,errors

**Comment by dayiguizhen** [comment]
Yeah,I found the mistake
The mistake is I forget register main blueprint in app/\__init\__.py
Now , I add the follow in app/\__init\__.py

from .main import main as main_blueprint;
app.register_blueprint(main_blueprint);

But it show me other error.
TypeError: 'NoneType' object is not callable

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 300, in _load_user
    return self.reload_user()
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 281, in reload_user
    user = self.user_callback(user_id)
TypeError: 'NoneType' object is not callable

**Comment by dayiguizhen** [comment]
Never mind. It was because I was missing user_loader.


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id));

**Comment by ithinco** [comment]
@miguelgrinberg 

I also got a similar error. When I visit  "localhost:5000/", I got an Error: BuildError: ('main.user', {}, None)

I registed main_blueprint, defined @login_manager.user_loader, route('/user/<username>') also exists

Traceback (most recent call last):
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ce/Desktop/workspace/sotech/app/main/views.py", line 19, in index
    return render_template('index.html', form=form, posts=posts, pagination=pagination)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ce/Desktop/workspace/sotech/app/templates/index.html", line 3, in top-level template code
    {% import "_macros.html" as macros %}
  File "/Users/ce/Desktop/workspace/sotech/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/ce/Desktop/workspace/sotech/app/templates/base.html", line 54, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/ce/Desktop/workspace/sotech/app/templates/index.html", line 21, in block "page_content"
    {% include '_posts.html' %}
  File "/Users/ce/Desktop/workspace/sotech/app/templates/_posts.html", line 6, in top-level template code
    <div class="post-author"><a href="{{ url_for('main.user', username=post.author.username) }}">{{ post.author.username }}</a></div>
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/Users/ce/Desktop/workspace/sotech/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('main.user', {}, None)

**Comment by miguelgrinberg** [comment]
@ithinco Your error is for the `main.user` route. Here is where it is defined: https://github.com/miguelgrinberg/flasky/blob/master/app/main/views.py#L61

Note that the route takes an argument, the username. The error indicates you are referencing this route without passing any arguments to url_for.

**Comment by ithinco** [comment]
@miguelgrinberg I get it. This is a really weird problem, cause I did add the 'username' argument to the route method "def user(username)".

**Comment by miguelgrinberg** [comment]
@ithinco this is error is about the way you invoke `url_for()`. You should do `url_for('main.user', username='my-username')`. Based on the error, I think you are doing `url_for('main.user')`.

**Comment by ithinco** [comment]
@miguelgrinberg I followed your instructions from Flasky repo's history, whenever I moved forward, I compared mine and your repo to see if I missed anything. And I did add the argument 'username=post.author.username' in '{{ url_for('main.user', username=post.author.username) }}' at '_posts.html'.

**Comment by 5imp1e** [comment]
hello, I also have the same issue as above. 
i think i have passed the arguments to url_for.
**why it also remind me of BuildError?**
the view.py
```
@main.route('/moderate/enbale/<int:id>')
@login_required
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    return redirect(url_for('.moderate',
                           page=request.args.get('page', 1, type=int)))
```
the _comment.html
```
{% if comment.disabled %}
    <a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enbale', id=comment.id, page=page) }}">Enable</a>
     {% else %}
     <a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_disable', id=comment.id, page=page) }}">Disable</a>

```
here is my trace of error:

```
Traceback (most recent call last):
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\Flask\test\venv\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "F:\Github\simp1e\app\main\views.py", line 82, in moderate
    pagination=pagination, page=page)
  File "F:\Flask\test\venv\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "F:\Flask\test\venv\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "F:\Flask\test\venv\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "F:\Flask\test\venv\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Github\simp1e\app\templates\moderate.html", line 2, in top-level template code
    {% import "_macro.html" as macro %}
  File "F:\Github\simp1e\app\templates\base.html", line 2, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "F:\Flask\test\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "F:\Flask\test\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "F:\Flask\test\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "F:\Flask\test\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "F:\Github\simp1e\app\templates\base.html", line 86, in block "content"
    {% block page_content %}
  File "F:\Github\simp1e\app\templates\moderate.html", line 11, in block "page_content"
    {% include '_comment.html' %}
  File "F:\Github\simp1e\app\templates\_comment.html", line 23, in top-level template code
    <a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enbale', id=comment.id, page=page) }}">Enable</a>
  File "F:\Flask\test\venv\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "F:\Flask\test\venv\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "F:\Flask\test\venv\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('main.moderate_enbale', {'id': 4, 'page': 1}, None)
```

**Comment by miguelgrinberg** [comment]
You have a typo: enbale != enable

**Comment by 5imp1e** [comment]
thanks for your attention.

could u tell where did it happen or how could i fix it

**Comment by miguelgrinberg** [comment]
search your entire code for "enbale" and you will find it.

**Comment by 5imp1e** [comment]
@miguelgrinberg Thanks a lot : ) 
what a stupid mistake...

**Comment by 5imp1e** [comment]
@miguelgrinberg  Sorry to bother u again.
but i ran into builderror again. :(  This time i have checked the spell to make sure no typo.
Is there any methods to deal the problem by myself ? I think the traceback hardly makes any sense when it ran into 'BuildError' .
And here is the code:
`views.py`
i try to add a function of deleting  comments
```
@main.route('/moderate/delete/<int:id>/')
@login_required
def comments_delete(id):
    comment = Comment.query.get_or_404(id)
    Comment.query.filter_by(comment=comment).delete()
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('.moderate',
                            page=request.args.get('page', 1, type=int)))
```
`_comments.html`
```
{% if moderate %}
    <br>                  
    <a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_delete', id=comment.id, page=page) }}">Delete</a>
```
`traceback`
`BuildError: ('main.moderate_delete', {'id': 15, 'page': 1}, None)`

```
Traceback (most recent call last):
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\Flask\test\venv\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "F:\Github\simp1e\app\main\views.py", line 104, in moderate
    pagination=pagination, page=page)
  File "F:\Flask\test\venv\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "F:\Flask\test\venv\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "F:\Flask\test\venv\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "F:\Flask\test\venv\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Github\simp1e\app\templates\moderate.html", line 2, in top-level template code
    {% import "_macro.html" as macro %}
  File "F:\Github\simp1e\app\templates\base.html", line 2, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "F:\Flask\test\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "F:\Flask\test\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "F:\Flask\test\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "F:\Flask\test\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "F:\Github\simp1e\app\templates\base.html", line 87, in block "content"
    {% block page_content %}
  File "F:\Github\simp1e\app\templates\moderate.html", line 11, in block "page_content"
    {% include '_comment.html' %}
  File "F:\Github\simp1e\app\templates\_comment.html", line 28, in top-level template code
    <a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_delete', id=comment.id, page=page) }}">Delete</a>
  File "F:\Flask\test\venv\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "F:\Flask\test\venv\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "F:\Flask\test\venv\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "F:\Flask\test\venv\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('main.moderate_delete', {'id': 15, 'page': 1}, None)
```
Thank u very much for your help.
: )

**Comment by miguelgrinberg** [comment]
Your function is called `comments_delete`, not `moderate_delete`.
