### ISSUE TITLE
issues with running my flask app

### ISSUE THREAD

**Issue by peterbayerle** [miguelgrinberg/flasky#437]
When I try to run my Flask app with flask run, I get the following error. (For context, I'm reading chapter 7 and have finished organizing the app into packages. `FLASK_APP="flasky.py"`

```
(venv) $ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/bin/flask", line 12, in <module>
    sys.exit(main())
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/venv/lib/python3.7/site-packages/flask/cli.py", line 117, in call_factory
    return app_factory(script_info)
  File "/Users/peterbayerle/Documents/Programming/Python projects/flasky/app/__init__.py", line 15, in create_app
    app.config.from_object(config[config_name])
KeyError: <flask.cli.ScriptInfo object at 0x103e1a940>
```

Anyone know the issue? Let me know if I should add more info about my code.

**Comment by PierreKimbanziR** [comment]
Hi ! 
I know its been two years but I am facing the same issue. Did you find a solution ? 
Thanks a lot
