### ISSUE TITLE
Cannot import SocketServer

### ISSUE THREAD

**Issue by ryanxjhan** [miguelgrinberg/flasky#439]
```
(venv) ~/Desktop/flask/flasky/app $ python3 models.py
Traceback (most recent call last):
  File "/Users/hans/Desktop/flask/flasky/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 56, in <module>
    from http.server import BaseHTTPRequestHandler
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 92, in <module>
    import email.utils
  File "/Users/hans/Desktop/flask/flasky/app/email.py", line 2, in <module>
    from flask import current_app, render_template
  File "/Users/hans/Desktop/flask/flasky/venv/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/Users/hans/Desktop/flask/flasky/venv/lib/python3.7/site-packages/flask/json/__init__.py", line 17, in <module>
    from werkzeug.http import http_date
  File "/Users/hans/Desktop/flask/flasky/venv/lib/python3.7/site-packages/werkzeug/http.py", line 43, in <module>
    from email.Utils import parsedate_tz
ModuleNotFoundError: No module named 'email.Utils'; 'email' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models.py", line 1, in <module>
    from werkzeug.security import generate_password_hash, check_password_hash
  File "/Users/hans/Desktop/flask/flasky/venv/lib/python3.7/site-packages/werkzeug/__init__.py", line 218, in <module>
    from .serving import run_simple
  File "/Users/hans/Desktop/flask/flasky/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 59, in <module>
    import SocketServer as socketserver
ModuleNotFoundError: No module named 'SocketServer'
```

**Comment by ryanxjhan** [comment]
I am using the latest version of everything.

**Comment by ryanxjhan** [comment]
Is this because there is file named email.py?

**Comment by miguelgrinberg** [comment]
Yes, you can't have email.py in the Python path.

**Comment by sanix-sandel** [comment]
Hello Miguel !
I have a problem, I'm about to deploy my web app using flask. but in your
tutorial, you said that Gmail is not a good option for production and
postfix or sendmail must be used. So how can I install and configure one of
them ? please I need your help.

Le dim. 1 déc. 2019 à 13:38, Miguel Grinberg <notifications@github.com> a
écrit :

**Comment by miguelgrinberg** [comment]
@sanix-sandel I intend to write a detailed tutorial at some point, but I haven't yet. I suggest you look for tutorials on digitalocean.com on how to set up an email server for your linux distribution, those are usually good.

**Comment by sanix-sandel** [comment]
Thank you very much for replying. I'm checking it out right now.

Le lun. 9 déc. 2019 à 02:38, Miguel Grinberg <notifications@github.com> a
écrit :
