### ISSUE TITLE
I'm a newbie, why can't I run it?

### ISSUE THREAD

**Issue by zhihuiyuze** [miguelgrinberg/flasky#461]
Hi, so let it run?
8.1 code
Use export FLASK_APP=__init__.py
`venv) [zhyz@zhyz-pc app]$ export FLASK_APP=__init__.py
(venv) [zhyz@zhyz-pc app]$ flask shell
Traceback (most recent call last):
  File "/home/zhyz/flasky/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/home/zhyz/flasky/venv/lib/python3.8/site-packages/flask/cli.py", line 117, in call_factory
    return app_factory(script_info)
  File "/home/zhyz/flasky/app/__init__.py", line 16, in create_app
    app.config.from_object(config[config_name])
KeyError: <flask.cli.ScriptInfo object at 0x7f30614d3850>
`
Use export FLASK_APP=models.py
`(venv) [zhyz@zhyz-pc app]$ export FLASK_APP=models.py
(venv) [zhyz@zhyz-pc app]$ flask shell
Usage: flask shell [OPTIONS]

Error: Failed to find Flask application or factory in module "app.models". Use "FLASK_APP=app.models:name to specify one.
`

**Comment by miguelgrinberg** [comment]
The `FLASK_APP` variable should be set to `flasky.py`. Why are you using other values?

**Comment by zhihuiyuze** [comment]
Thanks, I thought init was the main application. Also, I thought the second part of the book was independent.

**Comment by dreamerforxzc** [comment]
？？？？？？what？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"智慧雨泽"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 晚上7:54
收件人:&nbsp;"miguelgrinberg/flasky"<flasky@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [miguelgrinberg/flasky] I'm a newbie, why can't I run it? (#461)




Thanks, I thought init was the main application. Also, I thought the second part of the book was independent.

**Comment by zhihuiyuze** [comment]
> ？？？？？？什么？
> […](#)
> ------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：＆nbsp;“智慧雨泽“ <notifications@github.com> ;; 发送时间：＆nbsp; 2020年3月4日（星期三）晚上7:54收件人：“ miguelgrinberg / flasky” <flasky@noreply.github.com> ;; 抄送：“ Subscribed” <subscribed@noreply.github.com> ;; 主题：＆nbsp; Re：[miguelgrinberg / flasky]我是新手，为什么不能运行它？（[＃461](https://github.com/miguelgrinberg/flasky/issues/461)）谢谢，我认为init是主要应用程序。另外，我认为本书的第二部分是独立的。—您收到此消息是因为您已订阅该线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

I solved it now I can't find the main application
